"""CloudFront must never cache a liveness probe or a generated 5xx (#1520).

`/health` matched no `ordered_cache_behavior` in `infra/cloudfront.tf`, so it
fell through to `default_cache_behavior`, whose `html` cache policy has
`default_ttl = 60`. Measured on the live site: `x-cache: Hit from cloudfront`
with `age: 17`. A cached health check is not a health check — it keeps
answering "ok" for up to a minute after the origin has started failing, which
is the plausible-substitute degradation `docs/architectural-principles.md`
§ fail-soft names as the primary defect class.

The error half is worse and is what #1521's application-side `Cache-Control:
no-store` **cannot** reach. A 502/504 is generated by CloudFront or the ALB
when the origin does not answer, so there is no origin `Cache-Control` on it to
honour. Measured during the 2026-08-31 incident, three consecutive probes:

    health #1  code=504  total=90.40s   x-response-time-ms: 3203.0
    health #2  code=504  total=0.12s
    health #3  code=504  total=0.07s

The application answered #1 in 3.2s while the client saw a 504 at 90.4s; #2 and
#3 returned far too fast to have reached the origin. Those were cached 504s,
and they masked real state for the duration of the incident.

These tests read `infra/cloudfront.tf` as text and model CloudFront's own
first-match cache-behaviour resolution against the live route table. They are
hermetic by construction: no AWS, no terraform binary, no network, no `.env`,
no DB — the only inputs are a file in the repo and the FastAPI app's route
list.

`terraform validate` cannot catch any of this. A missing behaviour, a behaviour
bound to the wrong cache policy, and a behaviour ordered behind a broader
pattern that swallows it are all syntactically valid HCL.

Run:
    /path/to/env/bin/pytest backend/tests/test_cloudfront_health_uncached.py -q
"""

from __future__ import annotations

import re
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[2]
CLOUDFRONT_TF = REPO_ROOT / "infra" / "cloudfront.tf"

# The AWS-managed CachingDisabled policy, referenced through the data source
# declared at the bottom of cloudfront.tf. Spelled out rather than pattern-
# matched on "disabled" so a rename to a *different* policy fails here.
CACHING_DISABLED = "data.aws_cloudfront_cache_policy.caching_disabled.id"
HTML_POLICY = "aws_cloudfront_cache_policy.html.id"
STATIC_POLICY = "aws_cloudfront_cache_policy.static_assets.id"

# Origin-failure status codes CloudFront generates itself. 403/404 are
# deliberately absent: a missing static asset is a stable fact and caching it is
# correct, and this issue's anti-goals scope the change to error masking.
UNCACHEABLE_5XX = (500, 502, 503, 504)

# The `html` policy's TTLs are deliberate and out of scope (#1520 anti-goal:
# "Don't change the `html` policy's TTLs; the problem is that `/health` matches
# it at all"). Pinned so a well-meaning "fix" that lowers them instead of adding
# the behaviour fails loudly.
HTML_POLICY_TTLS = {"default_ttl": "60", "min_ttl": "0", "max_ttl": "60"}

# Behaviours that were already correct before this change (#1520 anti-goal:
# "Don't touch /api/*, /events/* or the static-asset behaviours").
PREEXISTING_BEHAVIOURS = {
    "/api/*": CACHING_DISABLED,
    "/events/*": CACHING_DISABLED,
    "/assets/*": STATIC_POLICY,
    "/static/*": STATIC_POLICY,
    "*.js": STATIC_POLICY,
    "*.css": STATIC_POLICY,
}

# Paths that must keep reaching the 60s-cached default behaviour. If an
# over-broad new pattern (`/*`, `*`) is ever added to make the liveness tests
# pass, HTML caching dies silently — these catch that.
STILL_CACHED_PATHS = ("/", "/index.html", "/explore")

DISTRIBUTION = 'resource "aws_cloudfront_distribution" "main"'
HTML_CACHE_POLICY = 'resource "aws_cloudfront_cache_policy" "html"'

# Anchors around the file-header comment that claims which paths are uncached.
HEADER_REGION = ("# Edge layer that sits in front of the existing ALB", "#   - Origin Shield in us-east-1")

_ATTR_RE = re.compile(r"^[ \t]*([A-Za-z_]\w*)[ \t]*=[ \t]*(.+?)[ \t]*$", re.MULTILINE)


# ── HCL reading ───────────────────────────────────────────────────────
#
# Parsed as text, not with an HCL library: adding a parser dependency to run
# one guard is a worse trade than 60 lines of brace matching, and the repo has
# the same shape already in backend/tests/test_ecs_backend_secrets.py.


def _tf_source() -> str:
    assert CLOUDFRONT_TF.is_file(), f"missing {CLOUDFRONT_TF}"
    return CLOUDFRONT_TF.read_text(encoding="utf-8")


def _mask(src: str) -> str:
    """Same-length copy with comment text and string *contents* blanked out.

    Brace matching and attribute scanning both run over this, so a `{` written
    inside a comment or a quoted string can never move a block boundary or
    invent an attribute. Length and indexes are preserved, so a span found here
    slices the original correctly.
    """
    out = list(src)
    i, n = 0, len(src)
    in_string = False
    while i < n:
        ch = src[i]
        if in_string:
            if ch == "\\":
                out[i] = " "
                if i + 1 < n:
                    out[i + 1] = " "
                i += 2
                continue
            if ch == '"':
                in_string = False
            else:
                out[i] = " "
            i += 1
            continue
        if ch == '"':
            in_string = True
            i += 1
            continue
        if ch == "#" or (ch == "/" and i + 1 < n and src[i + 1] == "/"):
            while i < n and src[i] != "\n":
                out[i] = " "
                i += 1
            continue
        i += 1
    return "".join(out)


def _brace_span(masked: str, open_idx: int) -> tuple[int, int]:
    depth = 0
    for i in range(open_idx, len(masked)):
        if masked[i] == "{":
            depth += 1
        elif masked[i] == "}":
            depth -= 1
            if depth == 0:
                return open_idx, i + 1
    raise AssertionError(f"unbalanced braces from offset {open_idx} in {CLOUDFRONT_TF}")


def _resource_span(header: str) -> tuple[int, int]:
    src, masked = _tf_source(), _mask(_tf_source())
    assert header in src, f"{header} not found in {CLOUDFRONT_TF} — did the file shape change?"
    start = src.index(header)
    return _brace_span(masked, masked.index("{", start))


def _sub_blocks(keyword: str) -> list[str]:
    """Every `<keyword> { ... }` block inside the distribution, in file order.

    Order is load-bearing: CloudFront takes the FIRST `ordered_cache_behavior`
    whose pattern matches, not the most specific one.
    """
    src = _tf_source()
    masked = _mask(src)
    d_start, d_end = _resource_span(DISTRIBUTION)
    body = masked[d_start:d_end]
    blocks = []
    for match in re.finditer(rf"(?m)^[ \t]*{re.escape(keyword)}[ \t]*\{{", body):
        _, end = _brace_span(body, match.end() - 1)
        blocks.append(src[d_start + match.start() : d_start + end])
    return blocks


def _attrs(block: str) -> dict[str, str]:
    """`{name: value}` for the top-level `name = value` lines of a block.

    Values are sliced from the ORIGINAL text at the span the masked copy
    matched, so string contents survive while comments never become attributes.
    """
    masked = _mask(block)
    return {m.group(1): block[m.start(2) : m.end(2)].strip().strip('"') for m in _ATTR_RE.finditer(masked)}


def _ordered_behaviours() -> list[dict[str, str]]:
    return [_attrs(b) for b in _sub_blocks("ordered_cache_behavior")]


def _default_behaviour() -> dict[str, str]:
    blocks = _sub_blocks("default_cache_behavior")
    assert len(blocks) == 1, f"expected exactly one default_cache_behavior, found {len(blocks)}"
    return _attrs(blocks[0])


def _error_responses() -> dict[int, dict[str, str]]:
    out = {}
    for block in _sub_blocks("custom_error_response"):
        attrs = _attrs(block)
        assert "error_code" in attrs, f"custom_error_response with no error_code:\n{block}"
        out[int(attrs["error_code"])] = attrs
    return out


def _header_comment() -> str:
    src = _tf_source()
    start_anchor, end_anchor = HEADER_REGION
    assert start_anchor in src, f"header anchor moved or was reworded: {start_anchor!r}"
    tail = src[src.index(start_anchor) :]
    assert end_anchor in tail, f"header anchor moved or was reworded: {end_anchor!r}"
    return tail[: tail.index(end_anchor)]


# ── CloudFront behaviour resolution ───────────────────────────────────


def _pattern_matches(pattern: str, path: str) -> bool:
    """CloudFront path-pattern semantics: `*` is any run of characters
    (including `/`), `?` is exactly one. Not `fnmatch`, which would also give
    `[...]` character-class meaning that CloudFront does not have.
    """
    regex = "".join(".*" if c == "*" else "." if c == "?" else re.escape(c) for c in pattern)
    return re.fullmatch(regex, path) is not None


def _resolve(path: str) -> tuple[str, str]:
    """(matched pattern, cache_policy_id) CloudFront would use for `path`."""
    for behaviour in _ordered_behaviours():
        if _pattern_matches(behaviour["path_pattern"], path):
            return behaviour["path_pattern"], behaviour.get("cache_policy_id", "")
    return "<default_cache_behavior>", _default_behaviour().get("cache_policy_id", "")


def _liveness_paths() -> list[str]:
    """Every registered GET route that is a liveness path.

    Enumerated from the app rather than hard-coded, so a health endpoint added
    later is covered by the CDN check the day it is added instead of the day
    someone remembers this file exists. Same helper shape as the sibling
    application-side guard, backend/tests/test_health_is_uncacheable.py.
    """
    from archimedes.main import app

    return sorted(
        {
            r.path
            for r in app.routes
            if getattr(r, "path", "").startswith(("/health", "/api/health")) and "GET" in getattr(r, "methods", set())
        }
    )


# ── Tests ─────────────────────────────────────────────────────────────


class TestTheReaderIsNotVacuous:
    """Guards the guard. Every assertion below is conditional on the parser
    actually finding blocks; a silently-empty parse would make the whole file
    pass against any input at all.
    """

    def test_the_distribution_is_found_and_has_ordered_behaviours(self):
        behaviours = _ordered_behaviours()
        assert len(behaviours) >= 8, f"only parsed {len(behaviours)} ordered_cache_behavior blocks"

    def test_every_behaviour_has_a_pattern_and_a_policy(self):
        for behaviour in _ordered_behaviours():
            assert "path_pattern" in behaviour, behaviour
            assert "cache_policy_id" in behaviour, behaviour
        assert "cache_policy_id" in _default_behaviour()

    def test_comments_are_not_parsed_as_attributes(self):
        """The blocks added by #1520 carry long `#` comments above them. If the
        masker regressed, comment prose would leak into `_attrs` and the
        pattern matching below would resolve against garbage.
        """
        patterns = [b["path_pattern"] for b in _ordered_behaviours()]
        assert all(p.startswith(("/", "*")) for p in patterns), patterns
        assert len(patterns) == len(set(patterns)), f"duplicate path_pattern: {patterns}"

    def test_liveness_route_enumeration_finds_routes(self):
        paths = _liveness_paths()
        assert len(paths) >= 5, paths
        assert "/health" in paths

    @pytest.mark.parametrize(
        ("pattern", "path", "expected"),
        [
            ("/health", "/health", True),
            ("/health", "/health/amm", False),  # exact patterns do not cover sub-paths
            ("/health", "/healthz", False),
            ("/health/*", "/health/amm", True),
            ("/health/*", "/health/paper-rag", True),
            ("/health/*", "/health", False),  # trailing `/` is literal
            ("/api/*", "/api/health", True),
            ("/api/*", "/api/health/amm", True),  # `*` spans `/`
            ("*.js", "/assets/app.js", True),
            ("/api/*", "/health", False),
        ],
    )
    def test_the_pattern_matcher_models_cloudfront(self, pattern: str, path: str, expected: bool):
        """A matcher that is too permissive would report coverage that does not
        exist. `/health` NOT matching `/health/amm` is the case that forces the
        second behaviour to exist.
        """
        assert _pattern_matches(pattern, path) is expected


class TestEveryLivenessPathBypassesTheEdgeCache:
    """Fails against `main` before #1520: `/health`, `/health/amm` and
    `/health/paper-rag` all resolved to `<default_cache_behavior>` and the
    `html` policy's 60s TTL.
    """

    @pytest.mark.parametrize("path", _liveness_paths())
    def test_path_resolves_to_caching_disabled(self, path: str):
        pattern, policy = _resolve(path)
        assert policy == CACHING_DISABLED, (
            f"{path} resolves to the {pattern!r} behaviour, whose cache_policy_id is "
            f"{policy!r}, not {CACHING_DISABLED}. CloudFront will cache the probe, so "
            f"it can report a stale 'ok' after the origin has started failing."
        )

    def test_both_health_patterns_are_declared_explicitly(self):
        """Coverage via some future catch-all would satisfy the test above
        while being the wrong fix. These two patterns must exist by name.
        """
        patterns = {b["path_pattern"] for b in _ordered_behaviours()}
        for required in ("/health", "/health/*"):
            assert required in patterns, f"no ordered_cache_behavior for {required!r}; found {sorted(patterns)}"

    def test_nothing_is_ordered_in_front_of_the_health_behaviours(self):
        """CloudFront takes the first matching behaviour, not the most specific.

        A broad pattern inserted above `/health` would recapture the liveness
        paths with no diff to the health blocks themselves — invisible to a
        reviewer reading only the added lines.
        """
        behaviours = _ordered_behaviours()
        first_health = next(i for i, b in enumerate(behaviours) if b["path_pattern"].startswith("/health"))
        for earlier in behaviours[:first_health]:
            for path in _liveness_paths():
                assert not _pattern_matches(earlier["path_pattern"], path), (
                    f"{earlier['path_pattern']!r} is ordered before the /health behaviours "
                    f"and matches {path}, so it wins first-match resolution"
                )


class TestGenerated5xxAreNotCached:
    """The half #1521's application header cannot reach.

    Fails against `main` before #1520: `infra/cloudfront.tf` had no
    `custom_error_response` block at all, so CloudFront's default error-caching
    TTL applied and one slow origin response became an instant 504 for every
    viewer at that POP.
    """

    @pytest.mark.parametrize("code", UNCACHEABLE_5XX)
    def test_error_code_is_declared(self, code: int):
        assert code in _error_responses(), (
            f"no custom_error_response for {code}. Without one, CloudFront applies "
            f"its default error-caching TTL and serves the generated error from the "
            f"edge — a 504 returned faster than a round trip to the origin."
        )

    @pytest.mark.parametrize("code", UNCACHEABLE_5XX)
    def test_error_caching_is_zero(self, code: int):
        # `.get(code, {})` rather than `[code]`: a missing block is already
        # reported by the test above, and a KeyError here would bury that
        # message under a stack trace instead of restating it.
        attrs = _error_responses().get(code, {})
        assert attrs.get("error_caching_min_ttl") == "0", (
            f"custom_error_response for {code} has "
            f"error_caching_min_ttl={attrs.get('error_caching_min_ttl')!r}; must be 0. "
            f"Declaring the block with a positive TTL is worse than not declaring it: "
            f"it reads as a fix while pinning the error for that many seconds."
        )

    @pytest.mark.parametrize("code", UNCACHEABLE_5XX)
    def test_the_origins_error_is_passed_through_unchanged(self, code: int):
        """`response_code` would rewrite the status an operator or the ALB sees.

        Turning a 504 into a 200 with a friendly page is a real CloudFront
        pattern and exactly the wrong thing here — it would make the liveness
        signal lie in the dangerous direction while every test above still
        passed.
        """
        attrs = _error_responses().get(code, {})
        assert "response_code" not in attrs, (
            f"custom_error_response for {code} rewrites the status to {attrs['response_code']}"
        )
        assert "response_page_path" not in attrs, f"custom_error_response for {code} substitutes a body"

    def test_no_5xx_is_left_cacheable(self):
        """Catches a 5xx block added later with a nonzero TTL."""
        offenders = {
            code: attrs.get("error_caching_min_ttl")
            for code, attrs in _error_responses().items()
            if 500 <= code < 600 and attrs.get("error_caching_min_ttl") != "0"
        }
        assert not offenders, f"5xx custom_error_response blocks with nonzero caching: {offenders}"


class TestAntiGoals:
    """#1520 stops `/health` matching the `html` policy. It must not change
    what that policy does, nor touch the behaviours that were already correct.
    """

    @pytest.mark.parametrize("path", STILL_CACHED_PATHS)
    def test_html_paths_still_reach_the_60s_default(self, path: str):
        pattern, policy = _resolve(path)
        assert pattern == "<default_cache_behavior>", f"{path} was captured by {pattern!r}"
        assert policy == HTML_POLICY, f"{path} now resolves to {policy!r}"

    @pytest.mark.parametrize(("ttl", "value"), sorted(HTML_POLICY_TTLS.items()))
    def test_the_html_policy_ttls_are_unchanged(self, ttl: str, value: str):
        start, end = _resource_span(HTML_CACHE_POLICY)
        assert _attrs(_tf_source()[start:end])[ttl] == value

    @pytest.mark.parametrize(("pattern", "policy"), sorted(PREEXISTING_BEHAVIOURS.items()))
    def test_preexisting_behaviour_is_untouched(self, pattern: str, policy: str):
        by_pattern = {b["path_pattern"]: b for b in _ordered_behaviours()}
        assert pattern in by_pattern, f"{pattern!r} behaviour was removed"
        assert by_pattern[pattern]["cache_policy_id"] == policy


class TestTheFileHeaderTellsTheTruth:
    """The header comment enumerates which paths are never cached. Prose that
    asserts a property is the same defect surface as code that does
    (CLAUDE.md § "A guard must be shown to reject something"), and this is the
    line a reader skims instead of counting behaviour blocks.
    """

    def test_the_header_names_every_uncached_pattern(self):
        header = _header_comment()
        uncached = [b["path_pattern"] for b in _ordered_behaviours() if b["cache_policy_id"] == CACHING_DISABLED]
        missing = [p for p in uncached if p not in header]
        assert not missing, (
            f"the file header lists the never-cached paths but omits {missing}. "
            f"Enumerate every one, or the next reader trusts a list that has "
            f"silently gone stale."
        )

    def test_the_header_mentions_the_error_caching_change(self):
        assert "error_caching_min_ttl" in _header_comment(), (
            "the header describes what the edge caches but not that generated "
            "5xx are exempt — the half of #1520 an application header cannot reach"
        )
