"""Strategy signal evaluator — paper-grounded strategies as live allocation signals.

Each strategy file in analytics-engine/strategies/ contains executable trading
logic encoded as a backtrader Strategy class. This module extracts the core
signal rule from each strategy and evaluates it against live market data,
producing a per-asset target weight.

No backtrader dependency — the signal rules are simple enough to evaluate
directly with numpy/pandas on a price DataFrame.

Design reference:
  - design.md § 4.3.2 (portfolio construction from strategy signals)
  - analytics-engine/strategies/*.py (source of truth for trading logic)
"""

from __future__ import annotations

import logging
import time
from dataclasses import dataclass
from enum import Enum
from typing import Any

import numpy as np
import pandas as pd

# Data-quality / fetch-verification harness (#772). verify_instrument is the
# per-ticker precondition every name must clear before admission to the universe
# below; verify_universe aggregates it. Re-exported so callers (and the universe
# parity test) gate GLOBAL_ASSETS on clean, gap-free, survivorship-aware data —
# poisoned history silently inflates Sharpe and corrupts the DSR/PBO gate.
from archimedes.services.data_quality import (  # noqa: F401 - re-exported for the universe-admission precondition
    UniverseReport,
    verify_instrument,
    verify_universe,
)

# REUSE the SAME spec validator the rigor gate runs, so an invalid spec fails
# loudly here exactly as it would at admission time. The condition-tree evaluator
# (``_eval_condition``) is the SAME one the backtest interpreter uses — imported
# LAZILY inside _spec_signal so this module does not pull backtrader into the
# API/runner import chain (the eager import would; _eval_condition itself is pure
# Python). Live↔backtest signal parity comes from sharing that one function.
from archimedes.services.strategy_dsl import DSLError, StrategySpec, validate_strategy_spec

logger = logging.getLogger(__name__)


# ─── Global asset universe ────────────────────────────────────────
# synth_symbol -> (yfinance_ticker, display_symbol, asset_class, exchange)
# The LIVE on-chain synth rows are GENERATED by scripts/generate_universe.py and
# stay parity-locked to the SSOT synthetics block (backend/archimedes/data/
# synthetic_universe.json) — every SSOT synth appears here so it is backtestable
# (test_universe_parity.py invariant 1). Coverage: broad/sector/thematic/style/
# international/bond/credit/commodity/metal/crypto/FX/volatility ETFs and pairs —
# NO single-name equities on the live path.
# The compliance-flagged single-name equities below are BACKTEST-ONLY (present
# here so they stay backtestable, but deliberately held OFF the on-chain SSOT
# pending compliance review — see synthetic_universe.json `_compliance_review`).
# Each entry is one tradable instrument; the agent ranks across all of them
# and the LLM portfolio agent can pick from any of them.
# To change the live universe: edit the curated list in generate_universe.py and
# re-run `--write` + `--print-global-assets`; do NOT hand-edit the live rows.
GLOBAL_ASSETS: dict[str, tuple[str, str, str, str]] = {
    # ── Live on-chain synths (generated by scripts/generate_universe.py; parity-locked ──
    # to the SSOT synthetics block). synth -> (yfinance_ticker, display, asset_class, exchange).
    "sAAVE": ("AAVE-USD", "AAVE", "crypto", "Coinbase"),
    "sACWI": ("ACWI", "ACWI", "intl_equity_etf", "NASDAQ"),
    "sADA": ("ADA-USD", "ADA", "crypto", "Coinbase"),
    "sAGG": ("AGG", "AGG", "us_bond_agg", "NYSE"),
    "sALGO": ("ALGO-USD", "ALGO", "crypto", "Coinbase"),
    "sANGL": ("ANGL", "ANGL", "credit_hy", "NASDAQ"),
    "sAPE": ("APE-USD", "APE", "crypto", "Coinbase"),
    "sAPT": ("APT-USD", "APT", "crypto", "Coinbase"),
    "sAR": ("AR-USD", "AR", "crypto", "Coinbase"),
    "sARB": ("ARB-USD", "ARB", "crypto", "Coinbase"),
    "sARGT": ("ARGT", "ARGT", "latam_equity_etf", "NYSE"),
    "sARKG": ("ARKG", "ARKG", "us_thematic_etf", "NYSE"),
    "sARKK": ("ARKK", "ARKK", "us_thematic_etf", "NYSE"),
    "sASHR": ("ASHR", "ASHR", "asia_equity_etf", "NYSE"),
    "sATOM": ("ATOM-USD", "ATOM", "crypto", "Coinbase"),
    "sAUDJPY": ("AUDJPY=X", "AUD/JPY", "fx", "OTC"),
    "sAUDUSD": ("AUDUSD=X", "AUD/USD", "fx", "OTC"),
    "sAVAX": ("AVAX-USD", "AVAX", "crypto", "Coinbase"),
    "sAXS": ("AXS-USD", "AXS", "crypto", "Coinbase"),
    "sBCH": ("BCH-USD", "BCH", "crypto", "Coinbase"),
    "sBIL": ("BIL", "BIL", "us_bond_tbill", "NYSE"),
    "sBKLN": ("BKLN", "BKLN", "credit_hy", "NYSE"),
    "sBNB": ("BNB-USD", "BNB", "crypto", "Coinbase"),
    "sBND": ("BND", "BND", "us_bond_agg", "NASDAQ"),
    "sBNDX": ("BNDX", "BNDX", "intl_bond", "NASDAQ"),
    "sBNO": ("BNO", "BNO", "energy_etf", "NYSE"),
    "sBOTZ": ("BOTZ", "BOTZ", "us_thematic_etf", "NASDAQ"),
    "sBTC": ("BTC-USD", "BTC", "crypto", "Coinbase"),
    "sBWX": ("BWX", "BWX", "intl_bond", "NYSE"),
    "sCHZ": ("CHZ-USD", "CHZ", "crypto", "Coinbase"),
    "sCIBR": ("CIBR", "CIBR", "us_thematic_etf", "NASDAQ"),
    "sCOPX": ("COPX", "COPX", "metal_eq_etf", "NYSE"),
    "sCORN": ("CORN", "CORN", "agri_etf", "NYSE"),
    "sCRV": ("CRV-USD", "CRV", "crypto", "Coinbase"),
    "sDASH": ("DASH-USD", "DASH", "crypto", "Coinbase"),
    "sDBA": ("DBA", "DBA", "commodity_etf", "NYSE"),
    "sDBB": ("DBB", "DBB", "commodity_etf", "NYSE"),
    "sDBC": ("DBC", "DBC", "commodity_etf", "NYSE"),
    "sDGRO": ("DGRO", "DGRO", "factor_etf", "NYSE"),
    "sDIA": ("DIA", "DIA", "us_equity_etf", "NYSE"),
    "sDOGE": ("DOGE-USD", "DOGE", "crypto", "Coinbase"),
    "sDOT": ("DOT-USD", "DOT", "crypto", "Coinbase"),
    "sDXJ": ("DXJ", "DXJ", "asia_equity_etf", "NYSE"),
    "sDYDX": ("DYDX-USD", "DYDX", "crypto", "Coinbase"),
    "sECH": ("ECH", "ECH", "latam_equity_etf", "NYSE"),
    "sEEM": ("EEM", "EEM", "em_equity_etf", "NYSE"),
    "sEFA": ("EFA", "EFA", "intl_equity_etf", "NYSE"),
    "sEGLD": ("EGLD-USD", "EGLD", "crypto", "Coinbase"),
    "sEIDO": ("EIDO", "EIDO", "asia_equity_etf", "NYSE"),
    "sEIRL": ("EIRL", "EIRL", "eu_equity_etf", "NYSE"),
    "sEMB": ("EMB", "EMB", "em_bond", "NASDAQ"),
    "sEMLC": ("EMLC", "EMLC", "em_bond", "NYSE"),
    "sENA": ("ENA-USD", "ENA", "crypto", "Coinbase"),
    "sENJ": ("ENJ-USD", "ENJ", "crypto", "Coinbase"),
    "sENZL": ("ENZL", "ENZL", "asia_equity_etf", "NASDAQ"),
    "sEPI": ("EPI", "EPI", "asia_equity_etf", "NYSE"),
    "sEPOL": ("EPOL", "EPOL", "eu_equity_etf", "NYSE"),
    "sETC": ("ETC-USD", "ETC", "crypto", "Coinbase"),
    "sETH": ("ETH-USD", "ETH", "crypto", "Coinbase"),
    "sEURCHF": ("EURCHF=X", "EUR/CHF", "fx", "OTC"),
    "sEURGBP": ("EURGBP=X", "EUR/GBP", "fx", "OTC"),
    "sEURJPY": ("EURJPY=X", "EUR/JPY", "fx", "OTC"),
    "sEURNOK": ("EURNOK=X", "EUR/NOK", "fx", "OTC"),
    "sEURSEK": ("EURSEK=X", "EUR/SEK", "fx", "OTC"),
    "sEURUSD": ("EURUSD=X", "EUR/USD", "fx", "OTC"),
    "sEWA": ("EWA", "EWA", "asia_equity_etf", "NYSE"),
    "sEWC": ("EWC", "EWC", "intl_equity_etf", "NYSE"),
    "sEWD": ("EWD", "EWD", "eu_equity_etf", "NYSE"),
    "sEWG": ("EWG", "EWG", "eu_equity_etf", "NYSE"),
    "sEWH": ("EWH", "EWH", "asia_equity_etf", "NYSE"),
    "sEWI": ("EWI", "EWI", "eu_equity_etf", "NYSE"),
    "sEWJ": ("EWJ", "EWJ", "asia_equity_etf", "NYSE"),
    "sEWK": ("EWK", "EWK", "eu_equity_etf", "NYSE"),
    "sEWL": ("EWL", "EWL", "eu_equity_etf", "NYSE"),
    "sEWM": ("EWM", "EWM", "asia_equity_etf", "NYSE"),
    "sEWN": ("EWN", "EWN", "eu_equity_etf", "NYSE"),
    "sEWO": ("EWO", "EWO", "eu_equity_etf", "NYSE"),
    "sEWP": ("EWP", "EWP", "eu_equity_etf", "NYSE"),
    "sEWQ": ("EWQ", "EWQ", "eu_equity_etf", "NYSE"),
    "sEWS": ("EWS", "EWS", "asia_equity_etf", "NYSE"),
    "sEWT": ("EWT", "EWT", "asia_equity_etf", "NYSE"),
    "sEWU": ("EWU", "EWU", "eu_equity_etf", "NYSE"),
    "sEWW": ("EWW", "EWW", "latam_equity_etf", "NYSE"),
    "sEWY": ("EWY", "EWY", "asia_equity_etf", "NYSE"),
    "sEWZ": ("EWZ", "EWZ", "latam_equity_etf", "NYSE"),
    "sEZA": ("EZA", "EZA", "intl_equity_etf", "NYSE"),
    "sEZU": ("EZU", "EZU", "eu_equity_etf", "NYSE"),
    "sFDN": ("FDN", "FDN", "us_thematic_etf", "NYSE"),
    "sFET": ("FET-USD", "FET", "crypto", "Coinbase"),
    "sFIL": ("FIL-USD", "FIL", "crypto", "Coinbase"),
    "sFLOT": ("FLOT", "FLOT", "credit_ig", "NYSE"),
    "sFLOW": ("FLOW-USD", "FLOW", "crypto", "Coinbase"),
    "sFXI": ("FXI", "FXI", "asia_equity_etf", "NASDAQ"),
    "sGALA": ("GALA-USD", "GALA", "crypto", "Coinbase"),
    "sGBPJPY": ("GBPJPY=X", "GBP/JPY", "fx", "OTC"),
    "sGBPUSD": ("GBPUSD=X", "GBP/USD", "fx", "OTC"),
    "sGDX": ("GDX", "GDX", "metal_eq_etf", "NYSE"),
    "sGDXJ": ("GDXJ", "GDXJ", "metal_eq_etf", "NYSE"),
    "sGLD": ("GLD", "GLD", "metal_etf", "NYSE"),
    "sGMX": ("GMX-USD", "GMX", "crypto", "Coinbase"),
    "sGOVT": ("GOVT", "GOVT", "us_bond_agg", "NYSE"),
    "sGRT": ("GRT-USD", "GRT", "crypto", "Coinbase"),
    "sGSG": ("GSG", "GSG", "commodity_etf", "NYSE"),
    "sGXG": ("GXG", "GXG", "latam_equity_etf", "NYSE"),
    "sHACK": ("HACK", "HACK", "us_thematic_etf", "NYSE"),
    "sHBAR": ("HBAR-USD", "HBAR", "crypto", "Coinbase"),
    "sHYG": ("HYG", "HYG", "credit_hy", "NYSE"),
    "sIAU": ("IAU", "IAU", "metal_etf", "NYSE"),
    "sIBB": ("IBB", "IBB", "us_thematic_etf", "NASDAQ"),
    "sICLN": ("ICLN", "ICLN", "commodity_etf", "NASDAQ"),
    "sICP": ("ICP-USD", "ICP", "crypto", "Coinbase"),
    "sIEF": ("IEF", "IEF", "us_bond_mid", "NYSE"),
    "sIEFA": ("IEFA", "IEFA", "intl_equity_etf", "NYSE"),
    "sIEMG": ("IEMG", "IEMG", "em_equity_etf", "NYSE"),
    "sIFRA": ("IFRA", "IFRA", "us_thematic_etf", "NYSE"),
    "sIGV": ("IGV", "IGV", "us_thematic_etf", "NASDAQ"),
    "sIJH": ("IJH", "IJH", "us_equity_etf", "NYSE"),
    "sIJR": ("IJR", "IJR", "us_equity_etf", "NYSE"),
    "sILF": ("ILF", "ILF", "latam_equity_etf", "NYSE"),
    "sIMX": ("IMX-USD", "IMX", "crypto", "Coinbase"),
    "sINDA": ("INDA", "INDA", "asia_equity_etf", "NASDAQ"),
    "sINJ": ("INJ-USD", "INJ", "crypto", "Coinbase"),
    "sIOTA": ("IOTA-USD", "IOTA", "crypto", "Coinbase"),
    "sITB": ("ITB", "ITB", "us_thematic_etf", "NYSE"),
    "sITOT": ("ITOT", "ITOT", "us_equity_etf", "NYSE"),
    "sIUSB": ("IUSB", "IUSB", "us_bond_agg", "NASDAQ"),
    "sIVV": ("IVV", "IVV", "us_equity_etf", "NYSE"),
    "sIWD": ("IWD", "IWD", "factor_etf", "NYSE"),
    "sIWF": ("IWF", "IWF", "factor_etf", "NYSE"),
    "sIWM": ("IWM", "IWM", "us_equity_etf", "NYSE"),
    "sIYR": ("IYR", "IYR", "reit_etf", "NYSE"),
    "sJETS": ("JETS", "JETS", "us_thematic_etf", "NYSE"),
    "sJNK": ("JNK", "JNK", "credit_hy", "NYSE"),
    "sJTO": ("JTO-USD", "JTO", "crypto", "Coinbase"),
    "sJUP": ("JUP-USD", "JUP", "crypto", "Coinbase"),
    "sKAS": ("KAS-USD", "KAS", "crypto", "Coinbase"),
    "sKAVA": ("KAVA-USD", "KAVA", "crypto", "Coinbase"),
    "sKRE": ("KRE", "KRE", "us_thematic_etf", "NYSE"),
    "sKSM": ("KSM-USD", "KSM", "crypto", "Coinbase"),
    "sKWEB": ("KWEB", "KWEB", "asia_equity_etf", "NYSE"),
    "sLDO": ("LDO-USD", "LDO", "crypto", "Coinbase"),
    "sLINK": ("LINK-USD", "LINK", "crypto", "Coinbase"),
    "sLIT": ("LIT", "LIT", "commodity_etf", "NYSE"),
    "sLQD": ("LQD", "LQD", "credit_ig", "NYSE"),
    "sLTC": ("LTC-USD", "LTC", "crypto", "Coinbase"),
    "sMBB": ("MBB", "MBB", "us_bond_agg", "NASDAQ"),
    "sMCHI": ("MCHI", "MCHI", "asia_equity_etf", "NASDAQ"),
    "sMDY": ("MDY", "MDY", "us_equity_etf", "NYSE"),
    "sMINA": ("MINA-USD", "MINA", "crypto", "Coinbase"),
    "sMINT": ("MINT", "MINT", "us_bond_tbill", "NYSE"),
    "sMOO": ("MOO", "MOO", "agri_etf", "NYSE"),
    "sMTUM": ("MTUM", "MTUM", "factor_etf", "NYSE"),
    "sMUB": ("MUB", "MUB", "us_muni", "NYSE"),
    "sNEAR": ("NEAR-USD", "NEAR", "crypto", "Coinbase"),
    "sNOBL": ("NOBL", "NOBL", "factor_etf", "NYSE"),
    "sNZDUSD": ("NZDUSD=X", "NZD/USD", "fx", "OTC"),
    "sOIH": ("OIH", "OIH", "us_thematic_etf", "NYSE"),
    "sONDO": ("ONDO-USD", "ONDO", "crypto", "Coinbase"),
    "sOP": ("OP-USD", "OP", "crypto", "Coinbase"),
    "sPALL": ("PALL", "PALL", "metal_etf", "NYSE"),
    "sPAVE": ("PAVE", "PAVE", "us_thematic_etf", "NYSE"),
    "sPDBC": ("PDBC", "PDBC", "commodity_etf", "NASDAQ"),
    "sPFF": ("PFF", "PFF", "credit_ig", "NASDAQ"),
    "sPOL": ("POL-USD", "POL", "crypto", "Coinbase"),
    "sPPLT": ("PPLT", "PPLT", "metal_etf", "NYSE"),
    "sPYTH": ("PYTH-USD", "PYTH", "crypto", "Coinbase"),
    "sQNT": ("QNT-USD", "QNT", "crypto", "Coinbase"),
    "sQQQ": ("QQQ", "QQQ", "us_equity_etf", "NASDAQ"),
    "sQUAL": ("QUAL", "QUAL", "factor_etf", "NYSE"),
    "sRENDER": ("RENDER-USD", "RENDER", "crypto", "Coinbase"),
    "sROBO": ("ROBO", "ROBO", "us_thematic_etf", "NYSE"),
    "sROSE": ("ROSE-USD", "ROSE", "crypto", "Coinbase"),
    "sRSP": ("RSP", "RSP", "us_equity_etf", "NYSE"),
    "sRUNE": ("RUNE-USD", "RUNE", "crypto", "Coinbase"),
    "sSAND": ("SAND-USD", "SAND", "crypto", "Coinbase"),
    "sSCHB": ("SCHB", "SCHB", "us_equity_etf", "NYSE"),
    "sSCHD": ("SCHD", "SCHD", "factor_etf", "NYSE"),
    "sSCHH": ("SCHH", "SCHH", "reit_etf", "NYSE"),
    "sSEI": ("SEI-USD", "SEI", "crypto", "Coinbase"),
    "sSHV": ("SHV", "SHV", "us_bond_tbill", "NASDAQ"),
    "sSHY": ("SHY", "SHY", "us_bond_short", "NYSE"),
    "sSIL": ("SIL", "SIL", "metal_eq_etf", "NYSE"),
    "sSKYY": ("SKYY", "SKYY", "us_thematic_etf", "NASDAQ"),
    "sSLV": ("SLV", "SLV", "metal_etf", "NYSE"),
    "sSMH": ("SMH", "SMH", "us_thematic_etf", "NASDAQ"),
    "sSNX": ("SNX-USD", "SNX", "crypto", "Coinbase"),
    "sSOL": ("SOL-USD", "SOL", "crypto", "Coinbase"),
    "sSOXX": ("SOXX", "SOXX", "us_thematic_etf", "NASDAQ"),
    "sSOYB": ("SOYB", "SOYB", "agri_etf", "NYSE"),
    "sSPLV": ("SPLV", "SPLV", "factor_etf", "NYSE"),
    "sSPY": ("SPY", "SPY", "us_equity_etf", "NYSE"),
    "sSTX": ("STX-USD", "STX", "crypto", "Coinbase"),
    "sSUI": ("SUI-USD", "SUI", "crypto", "Coinbase"),
    "sSVXY": ("SVXY", "SVXY", "volatility_etf", "NYSE"),
    "sTAN": ("TAN", "TAN", "commodity_etf", "NYSE"),
    "sTHD": ("THD", "THD", "asia_equity_etf", "NYSE"),
    "sTHETA": ("THETA-USD", "THETA", "crypto", "Coinbase"),
    "sTIA": ("TIA-USD", "TIA", "crypto", "Coinbase"),
    "sTIP": ("TIP", "TIP", "us_bond_tips", "NYSE"),
    "sTLT": ("TLT", "TLT", "us_bond_long", "NYSE"),
    "sTON": ("TON-USD", "TON", "crypto", "Coinbase"),
    "sTRX": ("TRX-USD", "TRX", "crypto", "Coinbase"),
    "sTUR": ("TUR", "TUR", "tr_equity_etf", "NYSE"),
    "sUNG": ("UNG", "UNG", "energy_etf", "NYSE"),
    "sUNI": ("UNI-USD", "UNI", "crypto", "Coinbase"),
    "sURA": ("URA", "URA", "commodity_etf", "NYSE"),
    "sUSDBRL": ("USDBRL=X", "USD/BRL", "fx", "OTC"),
    "sUSDCAD": ("USDCAD=X", "USD/CAD", "fx", "OTC"),
    "sUSDCHF": ("USDCHF=X", "USD/CHF", "fx", "OTC"),
    "sUSDCNH": ("USDCNH=X", "USD/CNH", "fx", "OTC"),
    "sUSDCZK": ("USDCZK=X", "USD/CZK", "fx", "OTC"),
    "sUSDHKD": ("USDHKD=X", "USD/HKD", "fx", "OTC"),
    "sUSDHUF": ("USDHUF=X", "USD/HUF", "fx", "OTC"),
    "sUSDILS": ("USDILS=X", "USD/ILS", "fx", "OTC"),
    "sUSDINR": ("USDINR=X", "USD/INR", "fx", "OTC"),
    "sUSDJPY": ("USDJPY=X", "USD/JPY", "fx", "OTC"),
    "sUSDKRW": ("USDKRW=X", "USD/KRW", "fx", "OTC"),
    "sUSDMXN": ("USDMXN=X", "USD/MXN", "fx", "OTC"),
    "sUSDNOK": ("USDNOK=X", "USD/NOK", "fx", "OTC"),
    "sUSDPLN": ("USDPLN=X", "USD/PLN", "fx", "OTC"),
    "sUSDSEK": ("USDSEK=X", "USD/SEK", "fx", "OTC"),
    "sUSDSGD": ("USDSGD=X", "USD/SGD", "fx", "OTC"),
    "sUSDTHB": ("USDTHB=X", "USD/THB", "fx", "OTC"),
    "sUSDTRY": ("USDTRY=X", "USD/TRY", "fx", "OTC"),
    "sUSDZAR": ("USDZAR=X", "USD/ZAR", "fx", "OTC"),
    "sUSMV": ("USMV", "USMV", "factor_etf", "NYSE"),
    "sUSO": ("USO", "USO", "energy_etf", "NYSE"),
    "sUVXY": ("UVXY", "UVXY", "volatility_etf", "NYSE"),
    "sVB": ("VB", "VB", "us_equity_etf", "NYSE"),
    "sVCIT": ("VCIT", "VCIT", "credit_ig", "NASDAQ"),
    "sVCSH": ("VCSH", "VCSH", "credit_ig", "NASDAQ"),
    "sVEA": ("VEA", "VEA", "intl_equity_etf", "NYSE"),
    "sVET": ("VET-USD", "VET", "crypto", "Coinbase"),
    "sVGIT": ("VGIT", "VGIT", "us_bond_mid", "NASDAQ"),
    "sVGLT": ("VGLT", "VGLT", "us_bond_long", "NASDAQ"),
    "sVGSH": ("VGSH", "VGSH", "us_bond_short", "NASDAQ"),
    "sVGT": ("VGT", "VGT", "us_thematic_etf", "NYSE"),
    "sVIG": ("VIG", "VIG", "factor_etf", "NYSE"),
    "sVLUE": ("VLUE", "VLUE", "factor_etf", "NYSE"),
    "sVNM": ("VNM", "VNM", "asia_equity_etf", "NYSE"),
    "sVNQ": ("VNQ", "VNQ", "reit_etf", "NYSE"),
    "sVNQI": ("VNQI", "VNQI", "reit_etf", "NASDAQ"),
    "sVO": ("VO", "VO", "us_equity_etf", "NYSE"),
    "sVOO": ("VOO", "VOO", "us_equity_etf", "NYSE"),
    "sVT": ("VT", "VT", "intl_equity_etf", "NYSE"),
    "sVTEB": ("VTEB", "VTEB", "us_muni", "NYSE"),
    "sVTI": ("VTI", "VTI", "us_equity_etf", "NYSE"),
    "sVTIP": ("VTIP", "VTIP", "us_bond_tips", "NASDAQ"),
    "sVTV": ("VTV", "VTV", "factor_etf", "NYSE"),
    "sVUG": ("VUG", "VUG", "factor_etf", "NYSE"),
    "sVWO": ("VWO", "VWO", "em_equity_etf", "NYSE"),
    "sVXUS": ("VXUS", "VXUS", "intl_equity_etf", "NASDAQ"),
    "sVXX": ("VXX", "VXX", "volatility_etf", "NYSE"),
    "sVYM": ("VYM", "VYM", "factor_etf", "NYSE"),
    "sWEAT": ("WEAT", "WEAT", "agri_etf", "NYSE"),
    "sWLD": ("WLD-USD", "WLD", "crypto", "Coinbase"),
    "sWOOD": ("WOOD", "WOOD", "commodity_etf", "NASDAQ"),
    "sXAG": ("SI=F", "SILVER_SPOT", "metal_spot", "COMEX"),
    "sXAU": ("GC=F", "GOLD_SPOT", "metal_spot", "COMEX"),
    "sXBI": ("XBI", "XBI", "us_thematic_etf", "NYSE"),
    "sXCU": ("HG=F", "COPPER_SPOT", "metal_spot", "COMEX"),
    "sXLB": ("XLB", "XLB", "us_sector_etf", "NYSE"),
    "sXLC": ("XLC", "XLC", "us_sector_etf", "NYSE"),
    "sXLE": ("XLE", "XLE", "us_sector_etf", "NYSE"),
    "sXLF": ("XLF", "XLF", "us_sector_etf", "NYSE"),
    "sXLI": ("XLI", "XLI", "us_sector_etf", "NYSE"),
    "sXLK": ("XLK", "XLK", "us_sector_etf", "NYSE"),
    "sXLM": ("XLM-USD", "XLM", "crypto", "Coinbase"),
    "sXLP": ("XLP", "XLP", "us_sector_etf", "NYSE"),
    "sXLRE": ("XLRE", "XLRE", "us_sector_etf", "NYSE"),
    "sXLU": ("XLU", "XLU", "us_sector_etf", "NYSE"),
    "sXLV": ("XLV", "XLV", "us_sector_etf", "NYSE"),
    "sXLY": ("XLY", "XLY", "us_sector_etf", "NYSE"),
    "sXME": ("XME", "XME", "metal_eq_etf", "NYSE"),
    "sXOP": ("XOP", "XOP", "us_thematic_etf", "NYSE"),
    "sXPD": ("PA=F", "PALL_SPOT", "metal_spot", "NYMEX"),
    "sXPT": ("PL=F", "PLAT_SPOT", "metal_spot", "NYMEX"),
    "sXRP": ("XRP-USD", "XRP", "crypto", "Coinbase"),
    "sXTZ": ("XTZ-USD", "XTZ", "crypto", "Coinbase"),
    "sYFI": ("YFI-USD", "YFI", "crypto", "Coinbase"),
    "sZEC": ("ZEC-USD", "ZEC", "crypto", "Coinbase"),
    # ── Compliance-flagged single-name equities: BACKTEST-ONLY (NOT in the live SSOT). ──
    # Present here so they stay backtestable; held off the on-chain path pending review
    # (see synthetic_universe.json `_compliance_review`).
    "sAAPL": ("AAPL", "AAPL", "us_stock", "NASDAQ"),
    "sMSFT": ("MSFT", "MSFT", "us_stock", "NASDAQ"),
    "sGOOGL": ("GOOGL", "GOOGL", "us_stock", "NASDAQ"),
    "sAMZN": ("AMZN", "AMZN", "us_stock", "NASDAQ"),
    "sNVDA": ("NVDA", "NVDA", "us_stock", "NASDAQ"),
    "sMETA": ("META", "META", "us_stock", "NASDAQ"),
    "sTSLA": ("TSLA", "TSLA", "us_stock", "NASDAQ"),
    "sAMD": ("AMD", "AMD", "us_stock", "NASDAQ"),
    "sAVGO": ("AVGO", "AVGO", "us_stock", "NASDAQ"),
    "sORCL": ("ORCL", "ORCL", "us_stock", "NYSE"),
    "sCRM": ("CRM", "CRM", "us_stock", "NYSE"),
    "sNFLX": ("NFLX", "NFLX", "us_stock", "NASDAQ"),
    "sJPM": ("JPM", "JPM", "us_stock", "NYSE"),
    "sBAC": ("BAC", "BAC", "us_stock", "NYSE"),
    "sGS": ("GS", "GS", "us_stock", "NYSE"),
    "sV": ("V", "V", "us_stock", "NYSE"),
    "sMA": ("MA", "MA", "us_stock", "NYSE"),
    "sBRK-B": ("BRK-B", "BRK.B", "us_stock", "NYSE"),
    "sLLY": ("LLY", "LLY", "us_stock", "NYSE"),
    "sUNH": ("UNH", "UNH", "us_stock", "NYSE"),
    "sJNJ": ("JNJ", "JNJ", "us_stock", "NYSE"),
    "sMRK": ("MRK", "MRK", "us_stock", "NYSE"),
    "sPFE": ("PFE", "PFE", "us_stock", "NYSE"),
    "sXOM": ("XOM", "XOM", "us_stock", "NYSE"),
    "sCVX": ("CVX", "CVX", "us_stock", "NYSE"),
    "sCOP": ("COP", "COP", "us_stock", "NYSE"),
    "sWMT": ("WMT", "WMT", "us_stock", "NYSE"),
    "sCOST": ("COST", "COST", "us_stock", "NASDAQ"),
    "sHD": ("HD", "HD", "us_stock", "NYSE"),
    "sPG": ("PG", "PG", "us_stock", "NYSE"),
    "sCOIN": ("COIN", "COIN", "us_stock", "NASDAQ"),
    "sMSTR": ("MSTR", "MSTR", "us_stock", "NASDAQ"),
    "sPLTR": ("PLTR", "PLTR", "us_stock", "NASDAQ"),
    "sASML": ("ASML", "ASML", "eu_stock", "AMS/NASDAQ"),
    "sSAP": ("SAP", "SAP", "eu_stock", "XETRA/NYSE"),
    "sNESN": ("NESN.SW", "NESN", "eu_stock", "SIX"),
    "sNOVO": ("NVO", "NVO", "eu_stock", "NYSE/Copenhagen"),
    "sAZN": ("AZN", "AZN", "eu_stock", "LSE/NASDAQ"),
    "sSHEL": ("SHEL", "SHEL", "eu_stock", "LSE/NYSE"),
    "sBP": ("BP", "BP", "eu_stock", "LSE/NYSE"),
    "sHSBC": ("HSBC", "HSBC", "eu_stock", "LSE/NYSE"),
    "sTTE": ("TTE", "TTE", "eu_stock", "Euronext/NYSE"),
    "sRHM": ("RHM.DE", "RHM", "eu_stock", "XETRA"),
    "sLVMH": ("MC.PA", "LVMH", "eu_stock", "Euronext"),
    "sSIE": ("SIE.DE", "SIE", "eu_stock", "XETRA"),
    "sTSM": ("TSM", "TSM", "asia_stock", "TWSE/NYSE"),
    "sBABA": ("BABA", "BABA", "asia_stock", "NYSE"),
    "sTM": ("TM", "TM", "asia_stock", "TSE/NYSE"),
    "sSONY": ("SONY", "SONY", "asia_stock", "TSE/NYSE"),
    "sSE": ("SE", "SE", "asia_stock", "NYSE"),
    "sTCEHY": ("TCEHY", "TCEHY", "asia_stock", "OTC"),
    "sTHYAO": ("THYAO.IS", "THYAO", "tr_stock", "BIST"),
    "sKCHOL": ("KCHOL.IS", "KCHOL", "tr_stock", "BIST"),
    "sGARAN": ("GARAN.IS", "GARAN", "tr_stock", "BIST"),
    "sASELS": ("ASELS.IS", "ASELS", "tr_stock", "BIST"),
    "sAKBNK": ("AKBNK.IS", "AKBNK", "tr_stock", "BIST"),
    "sSAHOL": ("SAHOL.IS", "SAHOL", "tr_stock", "BIST"),
    "sBIMAS": ("BIMAS.IS", "BIMAS", "tr_stock", "BIST"),
    "sEREGL": ("EREGL.IS", "EREGL", "tr_stock", "BIST"),
}


#: Declared-universe ticker → synth symbol. Lifted out of
#: ``evaluate_strategies``'s body (it was a local dict) so the paper-execution
#: pass can ask which synths a spec's ``asset_universe`` resolves to WITHOUT
#: copying the table (#1410: the paper path and the vault path share the signal
#: interpretation code, they do not each keep a version of it). Not derivable
#: from ``GLOBAL_ASSETS``: this maps the loose ticker names a spec declares
#: ("GOLD", "TREASURY") onto synths, while GLOBAL_ASSETS maps synths onto
#: vendor tickers ("GC=F"), and the two are not inverses.
TICKER_TO_SYNTH: dict[str, str] = {
    "SPY": "sSPY",
    "QQQ": "sQQQ",
    "IWM": "sIWM",
    "TSLA": "sTSLA",
    "NVDA": "sNVDA",
    "BTC": "sBTC",
    "ETH": "sETH",
    "GOLD": "sGOLD",
    "SILVER": "sSI",
    "COPPER": "sHG",
    "OIL": "sOIL",
    "BRENT": "sBRENT",
    "NATGAS": "sNG",
    "NIKKEI": "sNKY",
    "TREASURY": "sBIL",
    "BIL": "sBIL",
    "DAX": "sDAX",
    "FTSE": "sFTSE",
    "CAC": "sCAC",
    "BIST": "sBIST",
    "TUR": "sTUR",
}


def synths_for_universe(tickers: list[str]) -> list[str]:
    """Resolve a spec's declared ``asset_universe`` to synth symbols.

    Order-preserving and de-duplicated, mirroring what ``evaluate_strategies``
    does with the same map. A ticker that is already a synth symbol (a spec may
    declare ``"sSPY"`` directly) passes through; an unmappable one is DROPPED
    rather than guessed at — the evaluator's own fallback then decides what the
    strategy sees, which is the behaviour that already exists for vault
    strategies with unmappable universes.
    """
    out: list[str] = []
    seen: set[str] = set()
    for ticker in tickers:
        synth = TICKER_TO_SYNTH.get(ticker) or (ticker if ticker in GLOBAL_ASSETS else None)
        if synth and synth not in seen:
            out.append(synth)
            seen.add(synth)
    return out


def synth_display(synth: str) -> str:
    """Return the human-facing label for a synth symbol."""
    entry = GLOBAL_ASSETS.get(synth)
    return entry[1] if entry else synth


def synth_asset_class(synth: str) -> str:
    entry = GLOBAL_ASSETS.get(synth)
    return entry[2] if entry else "unknown"


# Universe scanned by `rank_market()` to surface top opportunities.
# A focused subset (~70 names) covering all asset classes; the LLM
# portfolio agent is allowed to pick any asset in GLOBAL_ASSETS, not
# only what's in this scan list.
DEFAULT_SCAN_UNIVERSE: list[str] = [
    "sSPY",
    "sQQQ",
    "sIWM",
    "sDIA",
    "sRSP",
    "sVTI",
    "sXLE",
    "sXLF",
    "sXLK",
    "sXLV",
    "sXLI",
    "sXLU",
    "sXLP",
    "sXLY",
    "sXLB",
    "sXLC",
    "sSMH",
    "sSOXX",
    "sARKK",
    "sIGV",
    "sMTUM",
    "sQUAL",
    "sUSMV",
    "sVLUE",
    "sVYM",
    "sSCHD",
    "sVEA",
    "sVWO",
    "sEFA",
    "sEEM",
    "sEWG",
    "sEWU",
    "sEWJ",
    "sEWY",
    "sMCHI",
    "sINDA",
    "sEWZ",
    "sTUR",
    "sTLT",
    "sIEF",
    "sSHY",
    "sBIL",
    "sAGG",
    "sBND",
    "sLQD",
    "sHYG",
    "sEMB",
    "sMUB",
    "sTIP",
    "sGLD",
    "sSLV",
    "sXAU",
    "sXAG",
    "sXCU",
    "sGDX",
    "sDBC",
    "sUSO",
    "sUNG",
    "sCORN",
    "sVXX",
    "sEURUSD",
    "sGBPUSD",
    "sUSDJPY",
    "sUSDTRY",
    "sAUDUSD",
    "sUSDCNH",
    "sBTC",
    "sETH",
    "sSOL",
    "sBNB",
    "sXRP",
    "sLINK",
    "sAVAX",
    "sDOGE",
]


# ─── Price cache (module-level, TTL-bounded) ───────────────────────
# yfinance is the bottleneck; without caching the advisor endpoint
# would refetch the full universe on every request.  TTL is short
# enough that intraday signals stay fresh.
_PRICE_CACHE: dict[str, tuple[pd.Series, float]] = {}
_CACHE_TTL_SEC = 600  # 10 minutes


def _cache_get(synth: str) -> pd.Series | None:
    entry = _PRICE_CACHE.get(synth)
    if entry is None:
        return None
    series, ts = entry
    if (time.time() - ts) > _CACHE_TTL_SEC:
        return None
    return series


def _cache_put(synth: str, series: pd.Series) -> None:
    _PRICE_CACHE[synth] = (series, time.time())


class Signal(Enum):
    """Strategy signal for a single asset."""

    LONG = "long"  # Full exposure
    FLAT = "flat"  # No exposure (in cash/USDC)
    SCALED = "scaled"  # Partial exposure (vol-targeting)


@dataclass
class AssetSignal:
    """A single strategy's signal for one asset."""

    strategy_id: str
    strategy_name: str
    asset: str  # e.g. "sSPY"
    signal: Signal
    weight: float  # 0.0 to 1.0 — target portfolio fraction for this asset
    reason: str  # Human-readable explanation


@dataclass
class StrategySignals:
    """All signals from one strategy across all assets."""

    strategy_id: str
    strategy_name: str
    paper_title: str
    signals: list[AssetSignal]
    paper_arxiv_id: str = ""

    @property
    def total_weight(self) -> float:
        return sum(s.weight for s in self.signals)


# ─── Price data helper ────────────────────────────────────────────


def verify_universe_data_quality(
    start: str,
    end: str,
    synths: list[str] | None = None,
    *,
    _downloader=None,
) -> UniverseReport:
    """Run the #772 data-quality harness over the universe's yfinance tickers.

    Precondition for the #759 universe expansion: a synth should be admitted to
    ``GLOBAL_ASSETS`` only if its underlying ticker passes ``verify_instrument``
    over the backtest window (fetchable, full-window, gap-free, survivorship-
    clean). Defaults to the current ``GLOBAL_ASSETS`` keys; pass ``synths`` to
    vet a candidate set before adding it. ``_downloader`` is injected by tests to
    mock the yfinance boundary. Returns the :class:`UniverseReport` — callers
    admit ``report.admitted`` and must exclude (never pad) ``report.rejected``.
    """
    keys = synths if synths is not None else list(GLOBAL_ASSETS.keys())
    tickers = [GLOBAL_ASSETS[s][0] for s in keys if s in GLOBAL_ASSETS]
    return verify_universe(tickers, start, end, _downloader=_downloader)


def _fetch_price_history(symbol: str, period: str = "2y") -> pd.Series:
    """Fetch daily closing prices for a single synth symbol (with cache).

    Used as a fallback; the batched variant below is preferred for
    multi-asset scans. Always daily — the vendor seam's cache
    (``asset_daily_bars``) is daily-grained; a prior ``interval`` parameter
    was dropped since every caller left it at its "1d" default anyway.

    Fetch goes through the market-data provider seam's ``daily`` half (#1218 /
    #1798: ``archimedes.services.market_data_provider``) rather than yfinance
    directly — vendor-swappable via ``MARKET_DATA_DAILY_PROVIDER``, and the
    provider's own Postgres cache means a warm request never re-hits the
    vendor live. This in-process ``_cache_get``/``_cache_put`` layer is
    unchanged (hot 600s TTL in front of that).
    """
    cached = _cache_get(symbol)
    if cached is not None:
        return cached

    entry = GLOBAL_ASSETS.get(symbol)
    if not entry:
        return pd.Series(dtype=float)
    yf_ticker = entry[0]

    try:
        from archimedes.services.market_data_provider import get_provider, provider_name

        fetched = get_provider(seam="daily").get_daily_close_batch({symbol: yf_ticker}, period=period)
        close = fetched.get(symbol)
        if close is None or close.empty:
            # Named, never silent (#1710) — same reason as the batch path below.
            logger.warning(
                "market-data gap: no price history for %s (%s) from provider %r (period=%s) — "
                "EXCLUDED, no series synthesized.",
                symbol,
                yf_ticker,
                provider_name("daily"),
                period,
            )
            return pd.Series(dtype=float)
        close = close.copy()
        close.name = symbol
        _cache_put(symbol, close)
        return close
    except Exception as e:
        logger.warning("Failed to fetch price history for %s (%s): %s", symbol, yf_ticker, e)
        return pd.Series(dtype=float)


def _fetch_price_histories(
    symbols: list[str],
    period: str = "2y",
) -> dict[str, pd.Series]:
    """Batch-fetch price histories for many synth symbols.

    Uses a single batched call to the market-data provider (#1218 seam) for
    everything that is not already in the in-process cache. Failed/empty
    tickers are simply omitted from the result. The provider's own
    ``asset_daily_bars`` Postgres cache sits underneath this — a cold
    in-process cache does not necessarily mean a live vendor hit; it may be
    served from Postgres instead.
    """
    result: dict[str, pd.Series] = {}
    # First pass: serve from cache
    to_fetch_synths: list[str] = []
    for sym in symbols:
        cached = _cache_get(sym)
        if cached is not None and not cached.empty:
            result[sym] = cached
        else:
            to_fetch_synths.append(sym)

    if not to_fetch_synths:
        return result

    # Build the ticker list (skip unknown synths)
    ticker_for_synth: dict[str, str] = {}
    for sym in to_fetch_synths:
        entry = GLOBAL_ASSETS.get(sym)
        if entry:
            ticker_for_synth[sym] = entry[0]
    if not ticker_for_synth:
        return result

    try:
        from archimedes.services.market_data_provider import get_provider

        fetched = get_provider(seam="daily").get_daily_close_batch(ticker_for_synth, period=period)
    except Exception as e:
        logger.warning("Batched market-data fetch failed: %s", e)
        # Fall back to per-symbol fetch for the ones we still need
        for sym in to_fetch_synths:
            series = _fetch_price_history(sym, period=period)
            if not series.empty:
                result[sym] = series
        return result

    for synth, series in fetched.items():
        if series is None or series.empty:
            continue
        series = series.copy()
        series.name = synth
        _cache_put(synth, series)
        result[synth] = series

    # Name the symbols the vendor had NO data for (#1710). The seam's
    # documented per-item-skip contract leaves an unfetchable ticker simply
    # ABSENT from `fetched`, so before this the only trace was whatever the
    # vendor library itself chose to print — for yfinance, a bare
    # "possibly delisted; no price data found" ERROR carrying vendor tickers
    # and no synth symbols, no provider name and no indication that the
    # evaluator then ran a strategy over a universe missing those names. This
    # line is the operator-legible half: which synths, which vendor tickers,
    # which provider. Excluded, never padded or forward-filled.
    missing = sorted(set(ticker_for_synth) - set(result))
    if missing:
        from archimedes.services.market_data_provider import provider_name

        logger.warning(
            "market-data gap: no price history for %d/%d requested symbols from provider %r "
            "(period=%s) — %s. These symbols are EXCLUDED from signal evaluation this run; "
            "no series is synthesized to replace them.",
            len(missing),
            len(ticker_for_synth),
            provider_name("daily"),
            period,
            ", ".join(f"{s}({ticker_for_synth[s]})" for s in missing),
        )

    return result


# ─── Signal evaluators — one per paper strategy ────────────────────
#
# Each evaluator is a pure function:
#   (asset_symbol, price_history) → AssetSignal
#
# The logic mirrors the backtrader Strategy class in the corresponding
# analytics-engine/strategies/ file.


def _faber_sma200_signal(
    strategy_id: str,
    asset: str,
    prices: pd.Series,
) -> AssetSignal:
    """Faber 2007 — long when close > SMA200, flat otherwise.

    Mirrors: FaberSMA200.next() in faber_2007_sma200_timing.py
    Rule: price > 200-day SMA → long; else → flat
    """
    sma_period = 200
    if len(prices) < sma_period + 1:
        return AssetSignal(
            strategy_id=strategy_id,
            strategy_name="Faber SMA200",
            asset=asset,
            signal=Signal.FLAT,
            weight=0.0,
            reason=f"Insufficient data ({len(prices)} bars, need {sma_period + 1})",
        )

    sma = prices.rolling(sma_period).mean()
    current_price = float(prices.iloc[-1])
    current_sma = float(sma.iloc[-1])

    if current_price > current_sma:
        return AssetSignal(
            strategy_id=strategy_id,
            strategy_name="Faber SMA200",
            asset=asset,
            signal=Signal.LONG,
            weight=1.0,
            reason=f"Price {current_price:.2f} > SMA200 {current_sma:.2f} → long",
        )
    return AssetSignal(
        strategy_id=strategy_id,
        strategy_name="Faber SMA200",
        asset=asset,
        signal=Signal.FLAT,
        weight=0.0,
        reason=f"Price {current_price:.2f} ≤ SMA200 {current_sma:.2f} → flat",
    )


def _vol_managed_signal(
    strategy_id: str,
    asset: str,
    prices: pd.Series,
    target_vol_annual: float = 0.15,
) -> AssetSignal:
    """Moreira & Muir 2017 — scale exposure by target_vol / realized_vol.

    Mirrors: VolatilityManagedLong.next() in moreira_muir_2017_volatility_managed.py
    Rule: exposure = min(target_vol / realized_vol_annual, 1.0)
    """
    vol_window = 22
    annualization = 252

    if len(prices) < vol_window + 1:
        return AssetSignal(
            strategy_id=strategy_id,
            strategy_name="Vol-Managed",
            asset=asset,
            signal=Signal.SCALED,
            weight=0.5,
            reason=f"Insufficient data ({len(prices)} bars), defaulting to 50%",
        )

    # Compute realized volatility from daily returns
    returns = prices.pct_change().dropna().tail(vol_window)
    if len(returns) < 2:
        return AssetSignal(
            strategy_id=strategy_id,
            strategy_name="Vol-Managed",
            asset=asset,
            signal=Signal.SCALED,
            weight=0.5,
            reason="Too few returns, defaulting to 50%",
        )

    realized_vol = float(returns.std() * np.sqrt(annualization))
    if realized_vol <= 0:
        return AssetSignal(
            strategy_id=strategy_id,
            strategy_name="Vol-Managed",
            asset=asset,
            signal=Signal.LONG,
            weight=1.0,
            reason="Zero realized vol → full exposure",
        )

    exposure = min(target_vol_annual / realized_vol, 1.0)
    current_price = float(prices.iloc[-1])

    signal_type = Signal.LONG if exposure >= 0.95 else Signal.SCALED
    return AssetSignal(
        strategy_id=strategy_id,
        strategy_name="Vol-Managed",
        asset=asset,
        signal=signal_type,
        weight=exposure,
        reason=f"Realized vol {realized_vol:.1%}, target {target_vol_annual:.0%} → exposure {exposure:.0%} (price {current_price:.2f})",
    )


def _tsmom_signal(
    strategy_id: str,
    asset: str,
    prices: pd.Series,
) -> AssetSignal:
    """Moskowitz, Ooi, Pedersen 2012 — long when 12-month return positive.

    Mirrors: TimeSeriesMomentum.next() in moskowitz_ooi_pedersen_2012_tsmom.py
    Rule: trailing 252-day return > 0 → long; else → flat
    """
    lookback = 252

    if len(prices) < lookback + 1:
        return AssetSignal(
            strategy_id=strategy_id,
            strategy_name="TSMOM",
            asset=asset,
            signal=Signal.FLAT,
            weight=0.0,
            reason=f"Insufficient data ({len(prices)} bars, need {lookback + 1})",
        )

    current_price = float(prices.iloc[-1])
    past_price = float(prices.iloc[-lookback - 1])
    trailing_return = (current_price / past_price) - 1.0

    if trailing_return > 0:
        return AssetSignal(
            strategy_id=strategy_id,
            strategy_name="TSMOM",
            asset=asset,
            signal=Signal.LONG,
            weight=1.0,
            reason=f"12m return {trailing_return:+.1%} ({past_price:.2f} → {current_price:.2f}) → long",
        )
    return AssetSignal(
        strategy_id=strategy_id,
        strategy_name="TSMOM",
        asset=asset,
        signal=Signal.FLAT,
        weight=0.0,
        reason=f"12m return {trailing_return:+.1%} ({past_price:.2f} → {current_price:.2f}) → flat",
    )


def _52w_high_signal(
    strategy_id: str,
    asset: str,
    prices: pd.Series,
) -> AssetSignal:
    """George & Hwang 2004 — long when price is within 5% of 52-week high.

    Mirrors: FiftyTwoWeekHigh in george_hwang_2004_52w_high.py
    Rule: proximity = price / 52w_high; long if proximity >= 0.95
    """
    lookback = 252
    if len(prices) < lookback:
        return AssetSignal(
            strategy_id=strategy_id,
            strategy_name="52W High",
            asset=asset,
            signal=Signal.FLAT,
            weight=0.0,
            reason=f"Insufficient data ({len(prices)} bars, need {lookback})",
        )

    high_52w = float(prices.rolling(lookback).max().iloc[-1])
    current = float(prices.iloc[-1])
    proximity = current / high_52w if high_52w > 0 else 0.0

    if proximity >= 0.95:
        return AssetSignal(
            strategy_id=strategy_id,
            strategy_name="52W High",
            asset=asset,
            signal=Signal.LONG,
            weight=proximity,
            reason=f"Price {current:.2f} is {proximity:.0%} of 52w high {high_52w:.2f} → long",
        )
    return AssetSignal(
        strategy_id=strategy_id,
        strategy_name="52W High",
        asset=asset,
        signal=Signal.FLAT,
        weight=0.0,
        reason=f"Price {current:.2f} is only {proximity:.0%} of 52w high {high_52w:.2f} → flat",
    )


def _buy_hold_signal(
    strategy_id: str,
    asset: str,
    prices: pd.Series,  # noqa: ARG001 — signature symmetry with other signal generators; buy-and-hold is always-on, no price input needed
) -> AssetSignal:
    """Buy-and-hold baseline — always fully invested."""
    return AssetSignal(
        strategy_id=strategy_id,
        strategy_name="Buy & Hold",
        asset=asset,
        signal=Signal.LONG,
        weight=1.0,
        reason="Buy-and-hold: always fully invested",
    )


# ─── DSL-spec evaluator — interprets a validated fusion spec live ──
#
# This is the path that kills the silent buy-and-hold fallback. A
# fusion-generated strategy carries a validated DSL spec (the same dict the
# rigor gate / backtest consume). Instead of keyword-matching the paper title
# into a hardcoded evaluator (and defaulting to always-long buy-and-hold when no
# keyword matches), we interpret the spec's entry/exit condition tree directly —
# computing each referenced indicator from the price Series with the SAME numpy/
# pandas primitives the 5 hardcoded evaluators use, then evaluating the tree with
# the SAME ``_eval_condition`` the backtest interpreter uses.

# Validated-spec cache: re-validating the DSL on every tick is wasteful. Keyed by
# id(spec_dict) is unsafe (dicts may be rebuilt), so key by the canonical JSON.
_SPEC_CACHE: dict[str, StrategySpec] = {}


def _validated_spec(spec_dict: dict[str, Any]) -> StrategySpec:
    """Validate a spec dict, caching the result. Raises DSLError on invalid spec."""
    import json

    try:
        key = json.dumps(spec_dict, sort_keys=True, default=str)
    except (TypeError, ValueError):
        key = None  # unhashable / non-serializable → skip cache, validate fresh

    if key is not None:
        cached = _SPEC_CACHE.get(key)
        if cached is not None:
            return cached

    spec = validate_strategy_spec(spec_dict)

    if key is not None:
        _SPEC_CACHE[key] = spec
    return spec


def _indicator_periods(spec: StrategySpec) -> dict[str, tuple[str, int]]:
    """Map indicator alias (e.g. ``"sma_200"``) → (name, period) for a spec."""
    out: dict[str, tuple[str, int]] = {}
    for alias in spec.indicators:
        parts = alias.rsplit("_", 1)
        if len(parts) == 2:
            try:
                out[alias] = (parts[0], int(parts[1]))
            except ValueError:
                continue
    return out


def _compute_indicator_value(name: str, period: int, prices: pd.Series) -> float:
    """Compute the latest value of one indicator from a price Series.

    Same numpy/pandas primitives as the 5 hardcoded evaluators, aligned with
    the backtrader interpreter's indicators (the backtest is what gets graded,
    so the live value must be computed the way the graded value was):
      - sma           → rolling(N).mean().iloc[-1]
      - ema           → ewm(span=N).mean().iloc[-1]  (first-value seeded; bt
                        seeds with an SMA — converges, known-benign F10)
      - rsi           → Wilder SMMA smoothing, seeded with the first-N SMA —
                        the algorithm behind bt.indicators.RSI's default
                        MovAv.Smoothed. NOT a plain rolling mean: that is
                        Cutler's RSI, a different indicator (7+ points apart
                        on short windows), and shipping it here while the
                        backtest used Wilder meant a threshold like rsi > 65
                        could pass in the graded backtest and fail live on
                        identical data (divergence audit F5).
      - momentum      → prices.iloc[-1] / prices.iloc[-N-1] - 1   (matches _tsmom_signal)
      - realized_vol  → pct_change().tail(N).std() * sqrt(252)    (matches _vol_managed_signal
                        AND, since 2026-08-30, dsl_to_backtrader.
                        RealizedVolAnnualized — a hand-written ddof=1 estimator
                        rather than bt.indicators.StandardDeviation, which is
                        ddof=0. Divergence audit F6 is CLOSED; the asymmetry pin
                        in test_interpreter_parity became a per-bar equality
                        pin. NOT the estimator the sizing branches use — see
                        dsl_to_backtrader.sizing_realized_vol.)
    """
    if name == "sma":
        return float(prices.rolling(period).mean().iloc[-1])
    if name == "ema":
        return float(prices.ewm(span=period, adjust=False).mean().iloc[-1])
    if name == "rsi":
        delta = prices.diff().dropna()
        if len(delta) < period:
            return float("nan")
        gain = delta.clip(lower=0.0)
        loss = -delta.clip(upper=0.0)
        # Wilder smoothing: seed with the plain mean of the first `period`
        # moves, then recurse avg = (avg*(period-1) + current) / period.
        # This is exactly backtrader's MovAv.Smoothed (SMA seed + recursive
        # exponential with alpha = 1/period), so the live RSI now equals the
        # backtested RSI to float precision on the same series — pinned by
        # the bt-parity test in test_dsl_rsi_parity.py.
        avg_gain = float(gain.iloc[:period].mean())
        avg_loss = float(loss.iloc[:period].mean())
        for g, lo in zip(gain.iloc[period:], loss.iloc[period:], strict=True):
            avg_gain = (avg_gain * (period - 1) + float(g)) / period
            avg_loss = (avg_loss * (period - 1) + float(lo)) / period
        if avg_loss == 0:
            return 100.0
        rs = avg_gain / avg_loss
        return float(100.0 - (100.0 / (1.0 + rs)))
    if name == "momentum":
        return float(prices.iloc[-1] / prices.iloc[-period - 1] - 1.0)
    if name == "realized_vol":
        return float(prices.pct_change().tail(period).std() * np.sqrt(252))
    raise DSLError(f"unsupported indicator: {name}")


def _rsi_wilder_series(prices: pd.Series, period: int) -> pd.Series:
    """Per-bar Wilder RSI — the whole-series twin of ``_compute_indicator_value``.

    Same seed (plain mean of the first ``period`` moves) and same recursion
    (``avg = (avg*(period-1) + current) / period``), just carried forward once
    instead of re-derived per prefix, so value[i] == the scalar the prefix
    ``prices.iloc[:i+1]`` would produce. NaN before the seed is complete.
    """
    n = len(prices)
    out = np.full(n, np.nan, dtype=float)
    if period < 1 or n < 2:
        return pd.Series(out, index=prices.index)

    raw = prices.to_numpy(dtype=float)
    diff = np.diff(raw)  # diff[k] is the move INTO price position k + 1
    # ``_compute_indicator_value`` drops NaN moves before seeding; mirror that
    # by carrying the kept moves' positions so a gap in the series shifts both
    # implementations identically instead of only one of them.
    kept = np.flatnonzero(~np.isnan(diff))
    if len(kept) < period:
        return pd.Series(out, index=prices.index)

    gains = np.where(diff > 0, diff, 0.0)[kept]
    losses = np.where(diff < 0, -diff, 0.0)[kept]
    avg_gain = float(gains[:period].mean())
    avg_loss = float(losses[:period].mean())

    def _rsi(ag: float, al: float) -> float:
        if al == 0:
            return 100.0
        return float(100.0 - (100.0 / (1.0 + ag / al)))

    out[kept[period - 1] + 1] = _rsi(avg_gain, avg_loss)
    for j in range(period, len(kept)):
        avg_gain = (avg_gain * (period - 1) + gains[j]) / period
        avg_loss = (avg_loss * (period - 1) + losses[j]) / period
        out[kept[j] + 1] = _rsi(avg_gain, avg_loss)
    return pd.Series(out, index=prices.index)


def _compute_indicator_series(name: str, period: int, prices: pd.Series) -> pd.Series:
    """Per-bar values of one indicator over the WHOLE series.

    The vectorised twin of ``_compute_indicator_value``: element *i* equals
    ``_compute_indicator_value(name, period, prices.iloc[: i + 1])`` for every
    bar the scalar form can compute, pinned per-bar by
    ``test_interpreter_parity.test_indicator_series_matches_per_prefix_value``.
    Existing to make the position-state replay (audit F2) O(bars) instead of
    O(bars²) — a per-prefix rescan of Wilder RSI on a 2-year window is ~125k
    Python iterations per (strategy, asset) per tick.

    NaN in the warm-up region is deliberate and load-bearing: the backtest reads
    an unready indicator as NaN too (``DSLStrategy._bar_values``'s IndexError
    guard), and NaN comparisons are False in ``_eval_condition`` — so a warm-up
    bar decides "no entry / no exit" on BOTH sides rather than diverging.
    """
    if name == "sma":
        return prices.rolling(period).mean().astype(float)
    if name == "ema":
        return prices.ewm(span=period, adjust=False).mean().astype(float)
    if name == "rsi":
        return _rsi_wilder_series(prices, period)
    if name == "momentum":
        return (prices / prices.shift(period) - 1.0).astype(float)
    if name == "realized_vol":
        # rolling().std() is NaN until a full window of returns exists, where the
        # scalar form's .tail(period).std() silently computes on a short window.
        # The replay only ever reads bars at/after max_period, so the two agree
        # everywhere the replay looks; the difference is confined to the warm-up
        # region the insufficient-data guard already refuses to trade on.
        return (prices.pct_change().rolling(period).std() * np.sqrt(252)).astype(float)
    raise DSLError(f"unsupported indicator: {name}")


# ─── Position-state replay — the live FSM (audit F2 + F3) ─────────
#
# THE DIVERGENCE THIS EXISTS FOR. The backtest is a position FSM
# (dsl_to_backtrader.DSLStrategy.next): entry is only tested while FLAT, exit is
# only tested while IN POSITION, and a bar where neither branch fires is an
# implicit HOLD. The live evaluator used to be stateless — ``entry AND NOT
# exit``, recomputed from scratch each tick with no memory — so an RSI 30/70
# band strategy was long in the backtest and in cash live on the very same bar
# (audit F2): the whole dead zone between the bands (30 <= rsi <= 70), where
# entry is false AND exit is false, collapsed to FLAT live.
#
# On top of that the live path never read ``rebalance_frequency`` at all (audit
# F3), so a spec declaring monthly cadence was re-decided on every one of the
# ~288 ticks a day, gated only by the runner's flat 15% drift threshold.
#
# STATE APPROACH: REPLAY-DERIVED, not persisted. The position is recomputed by
# replaying the spec's own FSM over the same price window the signal is computed
# from, every tick. Rationale:
#   * Deterministic and restart-safe — a redeploy, a crash, a Redis flush or a
#     second runner process all derive the SAME state from the same prices.
#     Persisted per-strategy state would silently reset to "flat" on restart,
#     which the FSM cannot tell from a genuine first entry.
#   * Exactly-once by construction. Signals are produced ONCE per tick per
#     (strategy, asset) but consumed by N vaults; a mutable persisted state
#     advanced in the per-vault loop would tick 2+ times per tick for a strategy
#     bound to 2+ vaults and corrupt its transitions. A pure function of the
#     price window cannot be double-advanced.
#   * No new persistence, no migration, no backfill, and nothing to reconcile
#     when a strategy is re-bound to a different vault.
#   * A missing-bars tick degrades honestly: the replay simply runs over the
#     bars that exist and the insufficient-data guard still refuses to trade —
#     it can never mistake a vendor gap for an exit, because there is no stored
#     "last position" for a gap to contradict.
# It matches how paper trading already derives position state (paper_trading.
# replay_spec re-runs the full backtest on every advance rather than
# checkpointing), so all three surfaces now agree by construction.
#
# KNOWN LIMIT, stated plainly: the cadence grid is anchored to the first
# post-warm-up bar of the window handed to the evaluator, exactly as the
# backtest anchors it (``_rebal_counter = period - 1``). Live, that window is a
# rolling 2-year fetch, so the grid's phase shifts by one bar per new trading
# day — a monthly strategy re-decides roughly every 21 bars, but not on a fixed
# calendar date. Intraday (the ~288-ticks-a-day case F3 is about) the daily bars
# are identical, so the position is provably constant within a day. A stable
# epoch anchor would fix the phase but would no longer match the backtest, and
# the backtest FSM is the semantic contract.
#
# SECOND KNOWN LIMIT — position MEMBERSHIP, not just phase (adversarial review
# of this change): the replay can only see entries inside the visible window.
# A position whose true entry bar has aged out of the rolling fetch's left
# edge (or sits inside the warm-up region) derives as FLAT here while the
# backtest, which saw the true entry, says LONG. Unreachable today — every
# live strategy is years younger than the fetch window — so the failure mode
# is guarded LOUDLY instead of redesigned: ``evaluate_strategies`` warns when
# a strategy's ``created_at`` predates its price window (see the guard there).
# Before any strategy approaches the window's age, the fetch must be anchored
# at strategy inception rather than rolling.


@dataclass(frozen=True)
class PositionReplay:
    """Position state derived by replaying a spec's FSM over a price window."""

    in_market: bool
    decision_index: int | None  # 0-based bar of the LAST cadence-eligible decision
    decision_count: int  # cadence-eligible bars the FSM actually evaluated
    entered_index: int | None  # bar the currently-open position was entered on


def _replay_position_state(
    spec: StrategySpec,
    prices: pd.Series,
    max_period: int,
) -> PositionReplay:
    """Replay the spec's position FSM over ``prices`` → state at the last bar.

    Bar-for-bar equivalent of ``DSLStrategy.next()``:
      * bars at index < ``max_period`` are warm-up and never decide anything
        (backtrader's ``len(self) <= self._warmup`` gate — the first bar the
        backtest can act on is 0-based index ``max_period``, for every
        indicator this DSL supports);
      * the cadence gate runs BEFORE the entry/exit branches, so an off-cadence
        bar is never even exit-tested (a held position stays held through it);
      * entry is only evaluated while flat, exit only while in position, and a
        bar where the active branch is false is a HOLD.

    Raises DSLError if the spec references an indicator this module cannot
    compute — the caller turns that into a loud FLAT, never a silent long.
    """
    from archimedes.services.dsl_to_backtrader import _eval_condition, rebalance_period_bars

    period_bars = rebalance_period_bars(spec.rebalance_frequency)
    closes = prices.to_numpy(dtype=float)
    n = len(closes)

    indicator_cols: dict[str, np.ndarray] = {
        alias: _compute_indicator_series(name, period, prices).to_numpy(dtype=float)
        for alias, (name, period) in _indicator_periods(spec).items()
    }

    in_market = False
    entered_index: int | None = None
    decision_index: int | None = None
    decision_count = 0

    for t in range(max_period, n):
        # Cadence gate FIRST — mirrors DSLStrategy._should_rebalance, whose
        # counter is seeded to period-1 so the first post-warm-up bar always
        # rebalances (offsets 0, period, 2*period, … from that bar).
        if period_bars > 1 and (t - max_period) % period_bars != 0:
            continue

        px = float(closes[t])
        bar_values: dict[str, float] = {
            "close": px,
            "open": px,
            "high": px,
            "low": px,
            "volume": 0.0,
        }
        for alias, col in indicator_cols.items():
            bar_values[alias] = float(col[t])

        decision_index = t
        decision_count += 1

        if not in_market:
            if _eval_condition(spec.entry, bar_values):
                in_market = True
                entered_index = t
        elif _eval_condition(spec.exit, bar_values):
            in_market = False
            entered_index = None

    return PositionReplay(
        in_market=in_market,
        decision_index=decision_index,
        decision_count=decision_count,
        entered_index=entered_index,
    )


def _spec_signal(
    strategy_id: str,
    asset: str,
    prices: pd.Series,
    spec_dict: dict[str, Any],
) -> AssetSignal:
    """Evaluate a validated DSL spec against live prices → AssetSignal.

    Pure Python — NO backtrader.Strategy / Cerebro / full backtest in the tick
    path. Validates the spec (cached), guards insufficient data, then REPLAYS the
    spec's position FSM over the price window (``_replay_position_state``) to get
    the state at the current bar, and sizes the position by
    ``position_sizing.type``.

    The replay is what makes this agree with the backtest (audit F2/F3): the
    position is HELD through the dead zone where entry and exit are both false,
    and entry/exit are only re-decided on bars the declared
    ``rebalance_frequency`` makes eligible. Sizing is evaluated as of that last
    decision bar, not the current one — otherwise an off-cadence bar could still
    move the target weight and re-open the hole F3 is about (for daily specs the
    two are the same bar, so daily behaviour is unchanged).

    On a DSLError (invalid spec) it logs loudly and returns a FLAT signal with an
    explicit reason — it NEVER silently buys-and-holds.
    """
    try:
        spec = _validated_spec(spec_dict)
    except DSLError as exc:
        logger.error(
            "DSL spec INVALID for strategy %s asset %s: %s — returning FLAT (no silent buy-and-hold)",
            strategy_id,
            asset,
            exc,
        )
        return AssetSignal(
            strategy_id=strategy_id,
            strategy_name="DSL (invalid spec)",
            asset=asset,
            signal=Signal.FLAT,
            weight=0.0,
            reason=f"spec invalid: {exc}",
        )

    strategy_name = spec.name or "DSL"
    periods = _indicator_periods(spec)
    max_period = max((p for _, p in periods.values()), default=0)

    # Guard insufficient data — need max_period + 1 bars to compute the longest
    # indicator (e.g. momentum_N reaches back N+1 bars).
    if len(prices) < max_period + 1 or len(prices) < 2:
        return AssetSignal(
            strategy_id=strategy_id,
            strategy_name=strategy_name,
            asset=asset,
            signal=Signal.FLAT,
            weight=0.0,
            reason=f"insufficient data ({len(prices)} bars, need {max_period + 1})",
        )

    # Replay the spec's position FSM over the window (audit F2 + F3). The
    # condition tree is evaluated inside the replay via the SAME
    # ``_eval_condition`` the backtest uses; ``_replay_position_state`` imports it
    # lazily so backtrader stays out of the API/runner module-load chain.
    try:
        replay = _replay_position_state(spec, prices, max_period)
    except DSLError as exc:
        logger.error(
            "DSL indicator compute failed for strategy %s asset %s: %s — returning FLAT",
            strategy_id,
            asset,
            exc,
        )
        return AssetSignal(
            strategy_id=strategy_id,
            strategy_name=strategy_name,
            asset=asset,
            signal=Signal.FLAT,
            weight=0.0,
            reason=f"spec invalid: {exc}",
        )

    close = float(prices.iloc[-1])
    cadence = spec.rebalance_frequency

    if replay.decision_index is None:
        # Unreachable given the insufficient-data guard above (bar max_period is
        # always cadence-eligible), but never imply a position that was never
        # derived — say so instead of falling through to a weight.
        return AssetSignal(
            strategy_id=strategy_id,
            strategy_name=strategy_name,
            asset=asset,
            signal=Signal.FLAT,
            weight=0.0,
            reason=f"no {cadence} decision bar in window ({len(prices)} bars)",
        )

    decision_index = replay.decision_index
    held_bars = len(prices) - 1 - decision_index
    cadence_note = f"{cadence} cadence, {replay.decision_count} decision bar(s), held {held_bars} bar(s) since"

    if not replay.in_market:
        return AssetSignal(
            strategy_id=strategy_id,
            strategy_name=strategy_name,
            asset=asset,
            signal=Signal.FLAT,
            weight=0.0,
            reason=f"position FSM → out of market ({cadence_note}; close={close:.2f})",
        )

    # Position sizing → weight, evaluated AS OF the last decision bar so an
    # off-cadence bar cannot move the target weight (see the docstring).
    decision_prices = prices.iloc[: decision_index + 1]
    ps = spec.position_sizing or {}
    ps_type = ps.get("type", "full_invested_when_in_market")

    if ps_type == "volatility_target":
        annual_pct = ps.get("annual_pct")
        # 22-day realized-vol window matches _vol_managed_signal's vol_window.
        realized_vol = _compute_indicator_value("realized_vol", 22, decision_prices)
        weight = 1.0 if not annual_pct or realized_vol <= 0 else min(float(annual_pct) / realized_vol, 1.0)
        signal_type = Signal.LONG if weight >= 0.95 else Signal.SCALED
        return AssetSignal(
            strategy_id=strategy_id,
            strategy_name=strategy_name,
            asset=asset,
            signal=signal_type,
            weight=round(weight, 4),
            reason=(
                f"in market since bar {replay.entered_index}; vol-target {annual_pct} / "
                f"realized {realized_vol:.1%} → weight {weight:.0%} ({cadence_note})"
            ),
        )

    if ps_type in ("equal_weight", "inverse_vol"):
        # Sized by the SAME module-level functions the backtest sizes with
        # (dsl_to_backtrader.slot_weight / sizing_realized_vol /
        # inverse_vol_weight), not by a second implementation of the same
        # arithmetic. Until 2026-08-30 this branch returned a flat 1.0 for both
        # types while the backtest sized them, so a spec's graded exposure and
        # its live exposure differed by up to N×.
        #
        # ``universe_slots`` is not a live concept: the evaluator emits one
        # signal per asset in the strategy's universe and the portfolio sums
        # them, which is exactly the single-feed convention (slots =
        # len(asset_universe)). The sleeve runners' ``universe_slots=1`` is a
        # backtest-side restatement of the same per-name weight, not a
        # different one — see interpret_spec's seam note.
        #
        # STILL DIVERGENT, and not silently: sizing TIMING. The backtest sizes
        # once at entry and freezes the share count; this recomputes at the last
        # decision bar. equal_weight is unaffected (1/N does not move);
        # inverse_vol agrees at the entry bar and drifts after it, exactly as
        # volatility_target already does. That is the unification plan's open D4
        # decision and is listed in the DSL spec's Known limitations.
        from archimedes.services.dsl_to_backtrader import (
            DEFAULT_INVERSE_VOL_REFERENCE,
            inverse_vol_weight,
            sizing_realized_vol,
            slot_weight,
        )

        slots = max(1, len(spec.asset_universe))
        slot = slot_weight(slots)
        if ps_type == "equal_weight":
            raw_weight = slot
            sizing_note = f"equal weight 1/{slots}"
        else:
            reference = float(ps.get("reference_vol_annual") or DEFAULT_INVERSE_VOL_REFERENCE)
            realized_vol = sizing_realized_vol(decision_prices.tolist())
            raw_weight = inverse_vol_weight(slot, realized_vol, reference)
            vol_note = "no vol estimate yet" if not realized_vol else f"realized {realized_vol:.1%}"
            sizing_note = f"inverse-vol slot 1/{slots} × ref {reference:.0%}/{vol_note}"
        # A weight above 1.0 is a leverage request. The backtest's cash broker
        # refuses it outright (margin-rejected, logged, flat); this portfolio has
        # no leverage either, so the live twin reports the clamp instead of
        # implying an exposure nothing can take. Reachable only for a
        # single-name inverse_vol universe on an asset calmer than the
        # reference — the one input class where the two sides disagree, pinned
        # by name in test_interpreter_parity and listed in the DSL spec's
        # Known limitations.
        weight = min(raw_weight, 1.0)
        clamp_note = f" (requested {raw_weight:.2f}, clamped — no leverage)" if raw_weight > 1.0 else ""
        return AssetSignal(
            strategy_id=strategy_id,
            strategy_name=strategy_name,
            asset=asset,
            signal=Signal.LONG if weight >= 0.95 else Signal.SCALED,
            weight=round(weight, 4),
            reason=(
                f"in market since bar {replay.entered_index}; {sizing_note} → weight "
                f"{weight:.0%}{clamp_note} ({cadence_note}; close={close:.2f})"
            ),
        )

    # full_invested_when_in_market → full exposure when in market.
    return AssetSignal(
        strategy_id=strategy_id,
        strategy_name=strategy_name,
        asset=asset,
        signal=Signal.LONG,
        weight=1.0,
        reason=f"in market since bar {replay.entered_index} ({cadence_note}; close={close:.2f}) → long",
    )


# ─── Strategy → evaluator mapping ─────────────────────────────────

# Maps strategy code_hash prefix to its evaluator function.
# In production, this would be auto-discovered from strategy metadata.
_STRATEGY_EVALUATORS: dict[str, callable] = {
    # faber_2007_sma200_timing.py
    "Faber": _faber_sma200_signal,
    "SMA200": _faber_sma200_signal,
    # moreira_muir_2017_volatility_managed.py
    "Volatility": _vol_managed_signal,
    "Vol-Managed": _vol_managed_signal,
    # moskowitz_ooi_pedersen_2012_tsmom.py
    "Time Series Momentum": _tsmom_signal,
    "TSMOM": _tsmom_signal,
    # george_hwang_2004_52w_high.py
    "52-Week": _52w_high_signal,
    "George": _52w_high_signal,
    "Hwang": _52w_high_signal,
    # pipeline_buy_hold.py
    "Buy-and-Hold": _buy_hold_signal,
}


def _get_evaluator(strategy_name: str, strategy_code_path: str | None = None) -> callable:
    """Find the evaluator function for a strategy by title or filename keyword match."""
    name_lower = strategy_name.lower()
    path_lower = (strategy_code_path or "").lower()
    combined = name_lower + " " + path_lower

    for keyword, evaluator in _STRATEGY_EVALUATORS.items():
        if keyword.lower() in combined:
            return evaluator
    # Default: buy-and-hold (always long)
    return _buy_hold_signal


# ─── Public API ────────────────────────────────────────────────────


class StrategySignalEvaluator:
    """Evaluates paper-grounded strategies against live market data.

    This IS the intelligence layer. No heuristics, no regime detector —
    the strategies themselves determine allocations through their
    published signal rules.
    """

    def evaluate_strategies(
        self,
        strategies: list,
        synth_assets: list[str],
        price_histories: dict[str, pd.Series] | None = None,
        scan_full_universe: bool = False,
    ) -> list[StrategySignals]:
        """Evaluate all strategies against live data.

        Args:
            strategies: List of Strategy dataclasses from LocalStrategyProvider
            synth_assets: List of synth symbols to evaluate (e.g. ["sSPY", "sTSLA"])
            price_histories: Optional pre-fetched price data. If None, fetches from yfinance.
            scan_full_universe: If True, every strategy evaluates against every
                asset in ``synth_assets`` regardless of its declared
                ``asset_universe``.  This is how the advisor "scans the market".

        Returns:
            List of StrategySignals, one per strategy.
        """
        # Fetch price histories if not provided
        if price_histories is None:
            price_histories = _fetch_price_histories(synth_assets, period="2y")

        if not price_histories:
            logger.warning("No price histories available — returning empty signals")
            return []

        # Map a strategy's declared asset_universe → synth symbols.
        synth_map = TICKER_TO_SYNTH

        results: list[StrategySignals] = []

        for strategy in strategies:
            if scan_full_universe:
                # Scan every asset in the supplied universe (the agent
                # is searching the market, not just rerunning paper-listed tickers).
                strategy_synths = [s for s in synth_assets if s in price_histories]
            else:
                strategy_synths = []
                seen_synths: set[str] = set()
                for ticker in strategy.asset_universe:
                    sym = synth_map.get(ticker)
                    if sym and sym in price_histories and sym not in seen_synths:
                        strategy_synths.append(sym)
                        seen_synths.add(sym)
                if not strategy_synths:
                    strategy_synths = list(price_histories.keys())

            # Per-strategy routing (claim-integrity fix). A fusion-generated
            # strategy carrying a validated DSL spec drives signals by SPEC
            # INTERPRETATION (live↔backtest parity via the shared condition tree).
            # Only strategies WITHOUT a spec fall back to the legacy keyword
            # evaluator. The path is logged once per strategy at INFO so the
            # fallback is no longer silent.
            spec_dict = getattr(strategy, "strategy_spec", None)
            use_spec = isinstance(spec_dict, dict) and bool(spec_dict)

            if use_spec:
                logger.info(
                    "Strategy '%s' → DSL-spec path (interpreting validated spec, %s cadence)",
                    strategy.paper_title,
                    spec_dict.get("rebalance_frequency", "unknown"),
                )
                # F2 known-limit guard (see the SECOND KNOWN LIMIT note above
                # _replay_position_state): a strategy older than its price
                # window can hold a position whose entry bar the replay cannot
                # see — it would read flat while the backtest reads long. No
                # strategy is near the window's age today; if this ever fires,
                # the fetch must be re-anchored at strategy inception before
                # this strategy's live signals are trusted. (Warm-up adds a
                # small extra blind margin beyond this comparison.)
                created_at = getattr(strategy, "created_at", None)
                window_start = min(
                    (price_histories[s].index[0] for s in strategy_synths if len(price_histories[s]) > 0),
                    default=None,
                )
                if created_at is not None and window_start is not None:
                    try:
                        created_ts = pd.Timestamp(created_at)
                        if created_ts.tzinfo is not None:
                            created_ts = created_ts.tz_localize(None)
                        window_ts = pd.Timestamp(window_start)
                        if window_ts.tzinfo is not None:
                            window_ts = window_ts.tz_localize(None)
                        if created_ts <= window_ts:
                            logger.warning(
                                "Strategy '%s' predates its price window (created %s <= window start %s): "
                                "a position entered before the window is INVISIBLE to the position replay "
                                "(F2 known limit) — re-anchor the price fetch at strategy inception before "
                                "trusting this strategy's live signals",
                                strategy.paper_title,
                                created_ts.date(),
                                window_ts.date(),
                            )
                    except (ValueError, TypeError):
                        logger.debug("could not compare created_at %r to window start", created_at)
                evaluator = lambda sid, asset, prices, _spec=spec_dict: _spec_signal(sid, asset, prices, _spec)  # noqa: E731
            else:
                evaluator = _get_evaluator(strategy.paper_title, strategy.strategy_code_path)
                logger.info(
                    "Strategy '%s' → legacy keyword path (evaluator=%s)",
                    strategy.paper_title,
                    getattr(evaluator, "__name__", str(evaluator)),
                )

            signals: list[AssetSignal] = []

            for asset in strategy_synths:
                prices = price_histories.get(asset)
                if prices is None or prices.empty:
                    continue
                signal = evaluator(strategy.id, asset, prices)
                signals.append(signal)

            if signals:
                results.append(
                    StrategySignals(
                        strategy_id=strategy.id,
                        strategy_name=strategy.paper_title,
                        paper_title=strategy.paper_title,
                        signals=signals,
                        paper_arxiv_id=strategy.paper_arxiv_id,
                    )
                )

                logger.info(
                    "Strategy '%s' scanned %d assets (long on %d)",
                    strategy.paper_title,
                    len(signals),
                    sum(1 for s in signals if s.signal != Signal.FLAT and s.weight > 0),
                )

        return results

    def rank_market(
        self,
        price_histories: dict[str, pd.Series],
        lookback_days: int = 90,
        top_n: int = 12,
    ) -> list[dict]:
        """Rank assets by recent risk-adjusted return (Sharpe-like).

        Returns a list sorted desc by score, with a dict per asset:
          { synth, display, asset_class, score, momentum, vol_ann }
        Used by the advisor to give strategies a focused "scan list"
        of the most promising opportunities globally.
        """
        ranked: list[dict] = []
        for synth, series in price_histories.items():
            if series.empty or len(series) < lookback_days + 1:
                continue
            window = series.tail(lookback_days + 1)
            returns = window.pct_change().dropna()
            if len(returns) < 5:
                continue
            mean_d = float(returns.mean())
            std_d = float(returns.std())
            if std_d <= 0 or not np.isfinite(std_d):
                continue
            momentum = float(window.iloc[-1] / window.iloc[0] - 1.0)
            sharpe_like = (mean_d / std_d) * float(np.sqrt(252))
            vol_ann = std_d * float(np.sqrt(252))
            entry = GLOBAL_ASSETS.get(synth)
            ranked.append(
                {
                    "synth": synth,
                    "display": entry[1] if entry else synth,
                    "asset_class": entry[2] if entry else "unknown",
                    "exchange": entry[3] if entry else "?",
                    "score": round(sharpe_like, 4),
                    "momentum_90d": round(momentum, 4),
                    "vol_ann": round(vol_ann, 4),
                }
            )
        ranked.sort(key=lambda r: r["score"], reverse=True)
        return ranked[:top_n]

    def aggregate_signals(
        self,
        all_signals: list[StrategySignals],
        usdc_floor: float = 0.20,
    ) -> dict[str, float]:
        """Aggregate strategy signals into target portfolio weights.

        Each strategy votes on each asset. Votes are averaged across
        strategies, then normalized to (1 - usdc_floor).

        Args:
            all_signals: Output of evaluate_strategies()
            usdc_floor: Minimum USDC allocation (0.0 to 1.0)

        Returns:
            Dict of symbol → target weight (all positive, sum to 1.0)
        """
        if not all_signals:
            return {"USDC": 1.0}

        # Collect votes per asset
        asset_votes: dict[str, list[float]] = {}
        for strat_signals in all_signals:
            for sig in strat_signals.signals:
                asset_votes.setdefault(sig.asset, []).append(sig.weight)

        # Average votes
        raw_weights: dict[str, float] = {}
        for asset, votes in asset_votes.items():
            raw_weights[asset] = sum(votes) / len(votes)

        # Scale to synth budget (1 - usdc_floor)
        synth_budget = 1.0 - usdc_floor
        total_raw = sum(raw_weights.values())

        normalized = {k: v / total_raw * synth_budget for k, v in raw_weights.items()} if total_raw > 0 else {}

        # Add USDC floor
        normalized["USDC"] = usdc_floor

        # Round and return
        return {k: round(v, 4) for k, v in sorted(normalized.items())}


# Singleton
strategy_evaluator = StrategySignalEvaluator()
