// /architecture — single-page infographic explaining how Archimedes actually
// works today: brief → debate-society generation → external rigor gate →
// inspect / explore. Vault execute / monitor is roadmap (flag-gated).
//
// Anti-rot rule (the reason the previous version of this page died): every
// number on this page is live-fetched on mount from /api/config/contracts,
// /health, and /api/leaderboard — never hardcoded. A failed fetch renders an
// honest "—" + "live value unavailable" caption, never a stale or invented
// number. See docs/architecture-redesign/ for the full design rationale.

import { useEffect, useState } from "react";
import { apiGet } from "../api";
import { fetchAgentStatus } from "../agentStatus";
import { fetchHealth } from "../health";
import flowDiagramSrc from "../assets/flow-diagram.svg";
import { ROADMAP_SURFACES_ENABLED } from "../featureFlags.js";
import { architecture as ROADMAP_COPY } from "../roadmapCopy.js";

function fmtNum(n) {
	return typeof n === "number" ? n.toLocaleString() : n;
}

// ── Live data ──────────────────────────────────────────────────────────

function useArchStats() {
	const [contracts, setContracts] = useState(null);
	const [contractsError, setContractsError] = useState(false);
	const [health, setHealth] = useState(null);
	const [healthError, setHealthError] = useState(false);
	const [leaderboard, setLeaderboard] = useState(null);
	const [leaderboardError, setLeaderboardError] = useState(false);
	const [agentStatus, setAgentStatus] = useState(null);
	const [agentStatusError, setAgentStatusError] = useState(false);

	useEffect(() => {
		apiGet("/api/config/contracts")
			.then(setContracts)
			.catch(() => setContractsError(true));
		// Shared TTL-cached call (#1333 review) — Layout.jsx's footer pill and
		// ModelCostPanel.jsx also read /health; fetchHealth() (../health.js)
		// lets a nav that lands here reuse Layout's just-fetched response
		// instead of firing a second Arc RPC round-trip + DB reads.
		fetchHealth()
			.then(setHealth)
			.catch(() => setHealthError(true));
		// scope=curated pinned deliberately: this stat is labeled "the public
		// leaderboard" / a library-wide count below, and the endpoint now
		// defaults to scope=own for a signed-in caller (leaderboard-goes-
		// single-user MVP) — an unpinned call would silently turn this into
		// the viewer's own strategy count for anyone signed in.
		apiGet("/api/leaderboard?scope=curated")
			.then(setLeaderboard)
			.catch(() => setLeaderboardError(true));
		// /api/agent/status.alive is the same Redis-heartbeat liveness check
		// vault_monitor.py surfaces per-vault (`agent_alive = age < 600`) —
		// the honesty ledger's rebalance-loop row reads it live rather than
		// asserting a static claim, same anti-rot rule as every other number
		// on this page (see the module docstring). TTL-cached the same way as
		// /health (#1382 review) — the endpoint does four Redis reads plus an
		// Arc RPC round-trip per call and carries no rate limit of its own.
		fetchAgentStatus()
			.then(setAgentStatus)
			.catch(() => setAgentStatusError(true));
	}, []);

	return {
		contracts,
		contractsError,
		health,
		healthError,
		leaderboard,
		leaderboardError,
		agentStatus,
		agentStatusError,
	};
}

// ── §1 — Header + hero stats ──────────────────────────────────────────

function PageHeader() {
	return (
		<div className="max-w-[820px] mb-7">
			<h1 className="text-[2rem] font-semibold mb-2.5">How Archimedes works</h1>
			<p className="body mb-2">
				{ROADMAP_SURFACES_ENABLED
					? "Archimedes turns quantitative-finance research into strategies you can actually inspect: generated by a multi-agent debate, admitted only through a statistical rigor gate, with every decision hashed on-chain before anything acts on it. The vault execution this preview build reveals is roadmap, not a live capability."
					: "Archimedes turns quantitative-finance research into strategies you can actually inspect: generated by a multi-agent debate, then admitted only through a statistical rigor gate. The shipped path is generate → rigor-gate → explore on Arc public testnet. Vault execute and monitor are roadmap."}
			</p>
			<p className="body" style={{ color: "var(--text-3)" }}>
				Everything on this page describes the live system — what runs today on
				the Arc public testnet, and what is landing next, labeled as such.
			</p>
		</div>
	);
}

// Skeleton → value → honest "—" on fetch error. Never renders undefined or
// a stale literal. `loading` and `failed` are passed explicitly (rather than
// inferred from `value == null`) so a genuine live "0" never gets mistaken
// for a still-loading state.
function StatTile({ label, value, caption, loading, failed }) {
	return (
		<div className="card-flat p-4">
			<div className="text-[1.8rem] font-bold" style={{ minHeight: "2.15rem" }}>
				{failed ? (
					<span style={{ color: "var(--text-4)" }}>—</span>
				) : loading ? (
					<span
						style={{ color: "var(--text-4)", animation: "pulse 1.4s infinite" }}
					>
						···
					</span>
				) : (
					fmtNum(value)
				)}
			</div>
			<div className="label mt-1">{label}</div>
			<div className="caption mt-1.5" style={{ color: "var(--text-3)" }}>
				{failed ? "live value unavailable" : caption}
			</div>
		</div>
	);
}

function HeroStrip({
	contracts,
	contractsError,
	health,
	healthError,
	leaderboard,
	leaderboardError,
}) {
	const synthCount = contracts?.synthetics
		? Object.keys(contracts.synthetics).length
		: undefined;
	const contractsLoading = !contracts && !contractsError;
	const healthLoading = !health && !healthError;
	const leaderboardLoading = !leaderboard && !leaderboardError;

	return (
		<div className="architecture-stats">
			<StatTile
				label="Tradable synthetic assets"
				value={synthCount}
				loading={contractsLoading}
				failed={contractsError}
				caption="live on Arc testnet"
			/>
			<StatTile
				label="Research papers in the corpus manifest"
				value={health?.corpus_papers}
				loading={healthLoading}
				failed={healthError}
				caption={
					health
						? `${fmtNum(health.corpus_db_count)} ingested and retrievable today`
						: ""
				}
			/>
			<StatTile
				label="Strategies on the public leaderboard"
				value={leaderboard?.total}
				loading={leaderboardLoading}
				failed={leaderboardError || leaderboard?.degraded}
				caption="ranked by real backtest + live rigor gate"
			/>
		</div>
	);
}

// ── §2 — The system, in one picture ───────────────────────────────────

// Gated whole: the diagram depicts the full off-chain → on-chain flow,
// including the vault/marketplace contracts at the bottom band, which have
// no reachable UI when ROADMAP_SURFACES_ENABLED is off (#1354). Vite's
// static asset import model can't cheaply build a flag-derived variant of
// an 18KB hand-authored SVG, and no acceptance check scans SVG content, so
// the honest fix at this granularity is to not show the diagram at all
// until the flow it depicts is reachable — matching how MarketplaceSection
// and AuthorityBoundary are gated at their mount site below.
function SystemFlowDiagram() {
	return (
		<div className="card p-5 mb-7">
			<div className="label mb-3">The system, in one picture</div>
			<div style={{ overflowX: "auto" }}>
				<img
					src={flowDiagramSrc}
					alt="Archimedes system flow: the user at top, Archimedes off-chain services in the
            middle, and Arc testnet contracts at the bottom, separated by a dashed trust boundary.
            The agent commits its reasoning hash on-chain before every trade and reveals the full
            trace afterward."
					style={{ width: "100%", minWidth: 640, display: "block" }}
				/>
			</div>
			<p className="caption mt-3" style={{ color: "var(--text-3)" }}>
				Off-chain, Archimedes reasons; on-chain, it is held to account. The
				dashed line is the trust boundary: everything below it is publicly
				verifiable on Arc, and the agent cannot cross it without committing its
				reasoning first.
			</p>
		</div>
	);
}

// ── §3 — The pipeline ──────────────────────────────────────────────────
// Numbered journey timeline. No separate "Portfolio Construction" stage
// exists: debate-society generation covers it. Five wallet
// signatures (not four — createVault + setAgent + approve + deposit +
// allocate, per CreateVaultModal.jsx), no invented tick interval (the
// backend doesn't expose AGENT_INTERVAL_SECONDS on any live endpoint, so it
// is omitted rather than guessed).
// Core steps: reachable regardless of the flag — the journey ends at the
// rigor verdict when ROADMAP_SURFACES_ENABLED is off (#1354). The roadmap
// tail (deploy → live execution → verify) only describes a real path once
// vault deploys are reachable, so it's appended only when the flag is on;
// flag-on rendering is byte-identical to the pre-#1354 six-step pipeline.
const CORE_PIPELINE_STEPS = [
	{
		title: "Your brief",
		sub: "plain English, optional asset classes, risk profile, and a model cost picker · your account owns the research; a wallet stays optional until an on-chain action",
	},
	{
		title: "Debate",
		sub: "proposer society drafts candidates from the research corpus and current market regime · adversarial critics + deterministic backtests cull them · one winner + considered-rejects",
	},
	{
		title: "Rigor gate",
		sub: "DSR, PBO, walk-forward out-of-sample, and a look-ahead audit — outside the generator, on real persisted returns",
		youAct: true,
		actLabel: "review the passport",
	},
];

// NOTE: the roadmap tail is built INLINE inside the ternary's truthy branch,
// not as a separately-declared const spread into it. A module-level
// `const ROADMAP_PIPELINE_STEPS = [...]` would construct that array (and
// evaluate every ROADMAP_COPY.* property read inside it) unconditionally at
// module load, regardless of which branch PIPELINE_STEPS below picks —
// defeating dead-code elimination of the ROADMAP_COPY strings from the
// flag-off bundle. Keeping the literal inline lets the bundler drop the
// entire unreached branch, roadmapCopy reads included — verified against
// issue #1354's acceptance criterion 1 dist-grep; see the PR body for the
// exact command and output.
const PIPELINE_STEPS = ROADMAP_SURFACES_ENABLED
	? [
			...CORE_PIPELINE_STEPS,
			{
				title: ROADMAP_COPY.pipelineDeployTitle,
				sub: "you sign every binding step: create the vault, authorize the agent, approve, deposit, allocate · the agent gets rebalance authority only",
				youAct: true,
				actLabel: ROADMAP_COPY.pipelineDeployActLabel,
			},
			{
				title: "Live execution",
				sub: "the agent ticks over your vault: evaluates the strategy's rule, commits its reasoning hash on-chain, trades, then reveals the full trace",
			},
			{
				title: "Verify & explore",
				sub: "recompute any trace hash against the on-chain anchor · browse your compounding library, the leaderboard, and the research underneath",
			},
		]
	: CORE_PIPELINE_STEPS;

function PipelineStep({ index, title, sub, youAct, actLabel, isLast }) {
	return (
		<div
			style={{
				display: "grid",
				gridTemplateColumns: "34px 1fr",
				columnGap: 16,
			}}
		>
			{/* Gutter: numbered node sitting on the continuous rail */}
			<div className="flex flex-col items-center">
				<div
					className="flex items-center justify-center font-semibold"
					style={{
						width: 32,
						height: 32,
						borderRadius: "50%",
						flexShrink: 0,
						fontSize: "0.85rem",
						fontVariantNumeric: "tabular-nums",
						// --accent-text, not --accent: the accent is a fill colour and is only
						// 3.91:1 as a numeral on the light theme's pale card. The filled
						// state needs --accent-on (pure white on light) rather than
						// --canvas, which is the tinted page ground and gave 4.16:1.
						color: youAct ? "var(--accent-on, var(--canvas))" : "var(--accent-text, var(--accent))",
						background: youAct ? "var(--accent)" : "var(--surface-1)",
						border: "1.5px solid var(--accent)",
						boxShadow: youAct ? "0 0 0 4px var(--accent-glow)" : "none",
						zIndex: 1,
					}}
				>
					{index + 1}
				</div>
				{!isLast && (
					<div
						style={{
							flex: 1,
							width: 2,
							minHeight: 20,
							background: "var(--accent)",
							opacity: 0.45,
						}}
					/>
				)}
			</div>

			{/* Content */}
			<div style={{ paddingBottom: isLast ? 0 : 20 }}>
				<div
					className="font-semibold flex items-center flex-wrap gap-x-2"
					style={{ fontSize: "0.95rem", minHeight: 32 }}
				>
					{title}
					{youAct && (
						<span
							className="label"
							style={{ color: "var(--accent-text, var(--accent))" }}
						>
							· you act: {actLabel}
						</span>
					)}
				</div>
				<div className="caption mt-0.5" style={{ color: "var(--text-3)" }}>
					{sub}
				</div>
			</div>
		</div>
	);
}

function PipelineFlow() {
	return (
		<div className="card p-5 mb-7">
			<div className="label mb-4">The pipeline</div>
			{PIPELINE_STEPS.map((step, i) => (
				<PipelineStep
					key={step.title}
					index={i}
					isLast={i === PIPELINE_STEPS.length - 1}
					{...step}
				/>
			))}
			<p
				className="caption mt-4"
				style={{
					color: "var(--text-3)",
					borderTop: "1px solid var(--glass-border)",
					paddingTop: 14,
				}}
			>
				{ROADMAP_SURFACES_ENABLED ? (
					<>
						You stay in the loop at two binding moments: reviewing the
						passport and signing the deploy steps. The agent cannot withdraw,
						cannot change what the vault may hold, and cannot trade without a
						prior on-chain commitment. If nothing clears the bar, Archimedes
						says so:{" "}
						<strong style={{ color: "var(--text-2)" }}>
							abstaining is a first-class outcome, not a failure state.
						</strong>
					</>
				) : (
					<>
						You stay in the loop at the one binding moment that exists today:
						reviewing the passport before anything runs. If nothing clears the
						bar, Archimedes says so:{" "}
						<strong style={{ color: "var(--text-2)" }}>
							abstaining is a first-class outcome, not a failure state.
						</strong>
					</>
				)}
			</p>
		</div>
	);
}

// ── §4 — Generation: the debate society ───────────────────────────────
// Replaces the old "3 top-level agents / Strategy Generation Agent with a
// Rigor Gate sub-agent" model. That architecture is wrong: generation is a
// multi-agent debate society (agents/debate_engine.py), and the rigor gate
// runs EXTERNAL to the generator (services/live_rigor_gate.py) so the thing
// being graded cannot influence its own grade. The Strategy Architect was
// removed entirely (PR #1074).
const DEBATE_STAGES = [
	{
		name: "Proposers",
		detail:
			"A pool of fusion agents, each drafting a strategy from a different slice of retrieved papers and regime context. Duplicate ideas are collapsed by content hash.",
	},
	{
		name: "Critics",
		detail:
			"An adversarial bull/bear round surfaces the strongest objections. It informs; it never decides.",
	},
	{
		name: "Deterministic judgment",
		detail:
			"Every surviving candidate is backtested in plain Python (zero LLM tokens), with the multiple-testing penalty counting every candidate tried, not just the winner.",
	},
	{
		name: "The null test",
		detail:
			"A candidate must beat simply buying and holding, net of costs. If none does, Archimedes abstains and shows you why.",
	},
];

function DebateSociety({ health, healthError }) {
	const modelLoading = !health && !healthError;
	return (
		<div className="mb-7">
			<div className="label mb-3">How a strategy is born</div>
			<p className="body mb-4">
				One agent brainstorming in a loop produces confident nonsense.
				Archimedes instead runs a <strong>debate society</strong> — the sole
				generation path:
			</p>
			<div className="grid grid-cols-1 md:grid-cols-2 gap-3 mb-4">
				{DEBATE_STAGES.map((s) => (
					<div key={s.name} className="card-flat p-4">
						<div className="font-semibold mb-1" style={{ fontSize: "0.92rem" }}>
							{s.name}
						</div>
						<p className="caption" style={{ color: "var(--text-3)" }}>
							{s.detail}
						</p>
					</div>
				))}
			</div>
			<div className="card p-4">
				<div className="label mb-2">Output</div>
				<p className="body mb-2" style={{ fontSize: "0.9rem" }}>
					One winner + the considered-rejects panel — what else was on the table
					and why it lost.
				</p>
				<p className="caption" style={{ color: "var(--text-3)" }}>
					LLM in use today:{" "}
					{healthError ? (
						<span style={{ color: "var(--text-4)" }}>
							— (live value unavailable)
						</span>
					) : modelLoading ? (
						<span
							style={{
								color: "var(--text-4)",
								animation: "pulse 1.4s infinite",
							}}
						>
							···
						</span>
					) : (
						<code>{health.llm_model}</code>
					)}{" "}
					via AWS Bedrock's Converse backend. The cost picker lets you pick a
					different model, bring your own key, or run fully local against
					Ollama.
				</p>
			</div>
		</div>
	);
}

// ── §5 — The rigor gate ────────────────────────────────────────────────
// The heaviest rewrite in this file. The spec's own draft copy ("corrected
// for how many things were tried") risked implying automatic multiple-
// testing correction. On the curated/library path, every strategy runs with
// num_trials=1 — backend/archimedes/services/rigor_evaluator.py logs it
// verbatim: "num_trials=1 — DSR runs UNDEFLATED (no multiple-testing
// correction)". The copy below states the defensible claim only, and names
// the num_trials=1 caveat explicitly rather than burying it.
function RigorGateSection({ leaderboard, leaderboardError }) {
	const loading = !leaderboard && !leaderboardError;

	return (
		<div className="card p-5 mb-7">
			<div className="label mb-3">
				The admission bar — computed live, never cached
			</div>
			<p className="body mb-4">
				Most backtests lie by selection: try enough ideas and one will look
				brilliant by chance. Over 20+ years of backtested returns net of
				realistic commission, a strategy's excess Sharpe must be positive at 95%
				one-sided confidence under standard errors robust to non-normality and
				autocorrelation, and must stay positive on a 30% chronological holdout.
				On the generated path, a strategy's Sharpe is additionally deflated
				against the size of its own candidate pool.
			</p>
			<div className="grid grid-cols-1 md:grid-cols-2 gap-3 mb-4">
				<div className="card-flat p-4">
					<div
						className="font-semibold mb-1"
						style={{ fontSize: "0.92rem" }}
						title="Deflated Sharpe Ratio"
					>
						DSR
					</div>
					<p className="caption" style={{ color: "var(--text-3)" }}>
						Deflated Sharpe Ratio: on generated strategies, deflates the Sharpe
						against how many candidates were tried in that debate round;
						curated-path strategies run with a single trial (see honesty note
						below).
					</p>
				</div>
				<div className="card-flat p-4">
					<div
						className="font-semibold mb-1"
						style={{ fontSize: "0.92rem" }}
						title="Probability of Backtest Overfitting"
					>
						PBO
					</div>
					<p className="caption" style={{ color: "var(--text-3)" }}>
						Probability of Backtest Overfitting: how likely the in-sample winner
						underperforms out-of-sample.
					</p>
				</div>
				<div className="card-flat p-4">
					<div
						className="font-semibold mb-1"
						style={{ fontSize: "0.92rem" }}
						title="Out-of-sample"
					>
						Walk-forward OOS
					</div>
					<p className="caption" style={{ color: "var(--text-3)" }}>
						The strategy must hold up on data it never saw, with no
						in-sample/out-of-sample cliff.
					</p>
				</div>
				<div className="card-flat p-4">
					<div className="font-semibold mb-1" style={{ fontSize: "0.92rem" }}>
						Look-ahead audit
					</div>
					<p className="caption" style={{ color: "var(--text-3)" }}>
						Static analysis confirms no future data leaks into any decision.
					</p>
				</div>
			</div>
			<div className="card-flat p-4">
				<div className="label mb-2">Honesty note</div>
				<p className="caption mb-2" style={{ color: "var(--text-3)" }}>
					The verdict is tri-state:{" "}
					<strong style={{ color: "var(--text-2)" }}>pass</strong>,{" "}
					<strong style={{ color: "var(--text-2)" }}>fail</strong>, or{" "}
					<strong style={{ color: "var(--text-2)" }}>pending</strong> (no real
					returns yet). A pending strategy is honestly unknown — it never
					silently wears a badge. Paper claims vs our replication are shown as
					deltas, not hidden behind a score. The gate is a bar, not a guarantee:
					passing reduces the odds of a curve-fit artifact; it does not promise
					alpha.
				</p>
				<p className="caption mb-3" style={{ color: "var(--text-3)" }}>
					On the curated library, <code>num_trials=1</code> — DSR runs
					undeflated (no multiple-testing correction) for those strategies.
				</p>
				<p
					className="caption"
					style={{
						color: "var(--text-3)",
						borderTop: "1px solid var(--glass-border)",
						paddingTop: 10,
					}}
				>
					How many curated-library strategies currently pass is unestablished —
					the live gate is the only authority, and this page will never quote a count.{" "}
					{leaderboardError ? (
						<span style={{ color: "var(--text-4)" }}>
							Live leaderboard size unavailable right now.
						</span>
					) : loading ? (
						<span
							style={{
								color: "var(--text-4)",
								animation: "pulse 1.4s infinite",
							}}
						>
							Loading live leaderboard…
						</span>
					) : (
						<>
							<strong style={{ color: "var(--text-1)" }}>
								{fmtNum(leaderboard.total)}
							</strong>{" "}
							strategies sit on the leaderboard today (that is a library size,
							not a pass count).
						</>
					)}
				</p>
			</div>
		</div>
	);
}

// ── §6 — On-chain execution (roadmap) ─────────────────────────────────
//
// This section used to be an unconditional present-tense claim
// ("Non-custodial by contract, not by promise" — "your deposit lives in a
// vault contract on Arc that you own") plus a four-row agent-authority
// table. It rendered regardless of ROADMAP_SURFACES_ENABLED, so the shipped
// public build asserted a capability with zero live user deployments behind
// it. Owner decision, 2026-08-30: this page keeps a LIMITED roadmap mention
// and nothing more; Landing and /security carry no mention at all. Do not
// re-add capability copy here until the path is live and reachable.
function OnChainExecutionRoadmap({ contracts, contractsError }) {
	return (
		<div className="card p-5 mb-7">
			<div className="label mb-3">On-chain execution — roadmap</div>
			<p className="body mb-3">
				<strong>
					Non-custodial vault execution is on the roadmap; not yet live.
				</strong>{" "}
				The contracts exist and are deployed to Arc testnet, but no user
				strategy runs against them today, and Archimedes does not manage capital.
				Everything else on this page describes a path that does run.
			</p>
			<p className="caption" style={{ color: "var(--text-3)" }}>
				Generation is not anchored on-chain today. The commit-before-trade
				loop is the vault-path mechanism, and vault execution is roadmap.
				Settlement, when execution ships, is USDC on Arc testnet
				{contractsError
					? " (chain id unavailable right now)"
					: contracts?.chain_id
						? ` chain ${contracts.chain_id}`
						: "…"}
				.
			</p>
		</div>
	);
}

// ── §7 — Provenance: commit → trade → reveal ───────────────────────────
// New section — the old page described publish-after anchoring; the real
// mechanism is commit-before-trade, contract-enforced (Vault.sol:422, #589).

function CommitTradeRevealLoop() {
	return (
		<svg
			viewBox="0 0 460 130"
			width="100%"
			height="130"
			role="img"
			aria-labelledby="ctr-title ctr-desc"
			style={{ maxWidth: 460, display: "block", margin: "0 auto" }}
		>
			<title id="ctr-title">Commit, trade, reveal in enforced order</title>
			<desc id="ctr-desc">
				Three-step loop: the agent commits a reasoning hash, the execution
				contract enforces that the trade cannot happen without that commitment,
				then the full trace is revealed and re-hashed on-chain to verify the
				match.
			</desc>
			<defs>
				<marker
					id="ctrArrow"
					viewBox="0 0 10 10"
					refX="8"
					refY="5"
					markerWidth="6"
					markerHeight="6"
					orient="auto-start-reverse"
				>
					<path d="M0,1 L9,5 L0,9 Z" fill="var(--accent)" />
				</marker>
				<marker
					id="ctrArrowMuted"
					viewBox="0 0 10 10"
					refX="8"
					refY="5"
					markerWidth="6"
					markerHeight="6"
					orient="auto-start-reverse"
				>
					<path d="M0,1 L9,5 L0,9 Z" fill="var(--text-3)" />
				</marker>
			</defs>
			<path
				d="M390,34 C390,6 70,6 70,34"
				fill="none"
				stroke="var(--text-3)"
				strokeWidth="1.2"
				strokeDasharray="3,3"
				markerEnd="url(#ctrArrowMuted)"
			/>
			<line
				x1="104"
				y1="65"
				x2="196"
				y2="65"
				stroke="var(--accent)"
				strokeWidth="1.5"
				markerEnd="url(#ctrArrow)"
			/>
			<line
				x1="264"
				y1="65"
				x2="356"
				y2="65"
				stroke="var(--accent)"
				strokeWidth="1.5"
				markerEnd="url(#ctrArrow)"
			/>
			{[
				{ x: 70, number: "1", label: "Commit" },
				{ x: 230, number: "2", label: "Trade" },
				{ x: 390, number: "3", label: "Reveal" },
			].map((node) => (
				<g key={node.label}>
					<circle
						cx={node.x}
						cy="65"
						r="34"
						fill="var(--surface-2)"
						stroke="var(--accent)"
						strokeWidth="1.5"
					/>
					<text
						x={node.x}
						y="61"
						textAnchor="middle"
						fontSize="11"
						fontWeight="600"
						fill="var(--text-1)"
					>
						{node.number}
					</text>
					<text
						x={node.x}
						y="76"
						textAnchor="middle"
						fontSize="10"
						fill="var(--text-3)"
					>
						{node.label}
					</text>
				</g>
			))}
		</svg>
	);
}

function ProvenanceSection() {
	return (
		<div className="card p-5 mb-7">
			<div className="label mb-3">Reasoning you can't backdate</div>
			<p className="body mb-4">
				A hash anchored <em>after</em> a trade proves nothing — you could
				generate a hundred rationales and keep the flattering one. Generation
				today computes a provenance hash and does <strong>not</strong> write it
				on-chain. The commit-before-trade loop below is the vault-path
				mechanism, and vault execution is roadmap:
			</p>
			<p className="caption mb-4" style={{ color: "var(--text-3)" }}>
				Read this as the ordering rule the contracts will enforce when that
				path ships, not as a claim that generation records the decision on Arc.
				The trade half belongs to the execution path described above as
				roadmap. No user vault has been deployed.
			</p>
			<div className="mb-4" style={{ overflowX: "auto" }}>
				<CommitTradeRevealLoop />
			</div>
			<div className="grid grid-cols-1 md:grid-cols-3 gap-3 mb-4">
				<div className="card-flat p-3">
					<div className="font-semibold mb-1" style={{ fontSize: "0.88rem" }}>
						1. Commit
					</div>
					<div className="caption" style={{ color: "var(--text-3)" }}>
						The agent hashes its full reasoning trace and records the hash +
						trade intent on the <code>ReasoningTraceRegistry</code>.
					</div>
				</div>
				<div className="card-flat p-3">
					<div className="font-semibold mb-1" style={{ fontSize: "0.88rem" }}>
						2. Trade
					</div>
					<div className="caption" style={{ color: "var(--text-3)" }}>
						The execution contract&apos;s <code>rebalance()</code> reverts unless
						that commitment exists — the ordering is enforced by the contract,
						not by our code being well-behaved.
					</div>
				</div>
				<div className="card-flat p-3">
					<div className="font-semibold mb-1" style={{ fontSize: "0.88rem" }}>
						3. Reveal
					</div>
					<div className="caption" style={{ color: "var(--text-3)" }}>
						After settlement, the full trace is published off-chain and the
						contract itself re-hashes the content to verify it matches the
						commitment. The on-chain keccak256 is the integrity anchor; we
						do not pin traces to IPFS.
					</div>
				</div>
			</div>
			<div className="card-flat p-4">
				<div className="label mb-2">Verify</div>
				<p className="caption" style={{ color: "var(--text-3)" }}>
					Open any decision in <strong>Reasoning</strong> and check two things:
					the content hash matches, and commit block &lt; trade block &lt;
					reveal block. This proves the trace existed before the trade and was
					never rewritten. It does not prove the reasoning was smart or the
					trade profitable — that honesty is the point.
				</p>
			</div>
		</div>
	);
}

// ── §8 — The marketplace ───────────────────────────────────────────────

function MarketplaceSection() {
	return (
		<div className="mb-7">
			<div className="label mb-3">{ROADMAP_COPY.marketplaceTitle}</div>
			<p className="body mb-4">
				Publish a strategy and others can subscribe to it for sub-cent USDC
				nanopayments (x402), settled through Circle's Gateway. Every payment
				splits <strong>90/10</strong> creator/platform through an on-chain{" "}
				<code>PaymentSplitter</code>. Subscribers get a dedicated Circle wallet
				provisioned automatically; spend caps bound what a runaway agent can
				spend. Archimedes earns generation and marketplace fees only — never a
				cut of anyone's trading P&amp;L, and never the other side of your trade.
			</p>
			<div className="card-flat p-4">
				<div className="label mb-2">Honesty note</div>
				<p className="caption" style={{ color: "var(--text-3)" }}>
					There is no vault principal today — that path is roadmap (see the
					on-chain execution section above), and when it ships the principal is
					non-custodial by contract. Marketplace fee custody is being migrated
					to a fully non-custodial design; fee settlement is currently in
					dry-run.
				</p>
			</div>
		</div>
	);
}

// ── §9 — The research corpus ───────────────────────────────────────────
// Every retrieval claim on this panel is driven off /health, never asserted
// statically — see #778. Two things this panel must NOT imply. (1) That a
// vector index sits behind the corpus: the papers schema carries text only,
// and /health says so directly now (#1488) — corpus_embedded_at_rest is false,
// while paper_rerank_model_live carries the narrower process-local fact of
// whether the MiniLM model loaded in *this* worker.
// (2) That a knowledge graph exists: corpus_kg_built is false and the
// graph/KG endpoints 503. backend/tests/test_corpus_claim_integrity.py
// scans this file for both claim-shapes.

function CorpusSection({ health, healthError }) {
	const loading = !health && !healthError;
	return (
		<div className="card p-5 mb-7">
			<div className="label mb-3">Where the ideas come from</div>
			{healthError ? (
				<p className="body mb-4" style={{ color: "var(--text-4)" }}>
					Live corpus stats are unavailable right now.
				</p>
			) : loading ? (
				<p
					className="body mb-4"
					style={{ color: "var(--text-4)", animation: "pulse 1.4s infinite" }}
				>
					Loading live corpus stats…
				</p>
			) : (
				<p className="body mb-4">
					Generation starts from a corpus of quantitative-finance research — a{" "}
					{fmtNum(health.corpus_papers)}-paper arXiv manifest spanning
					statistical finance, portfolio math, market microstructure, and
					agentic AI. At generate time, retrieval runs in two stages: a
					keyword/asset-class filter, then a relevance rerank against your brief,
					scored at request time over each candidate's title and abstract, with no
					vector index behind it (
					{health.paper_rag === "live"
						? "/health reports paper_rag: live — the rerank is running MiniLM sentence embeddings right now"
						: "/health reports paper_rag: degraded — the rerank is running the lexical TF-IDF fallback right now"}
					). Retrieved papers are embargo-filtered — nothing published after a
					decision point can inform it — and every citation carries its arXiv ID
					and content hash.
				</p>
			)}
			<div className="card-flat p-4">
				<div className="label mb-2">Honesty note</div>
				{healthError ? (
					<p className="caption" style={{ color: "var(--text-4)" }}>
						Live hydration status unavailable right now.
					</p>
				) : loading ? (
					<p
						className="caption"
						style={{ color: "var(--text-4)", animation: "pulse 1.4s infinite" }}
					>
						Loading…
					</p>
				) : (
					<p className="caption" style={{ color: "var(--text-3)" }}>
						{fmtNum(health.corpus_db_count)} of the{" "}
						{fmtNum(health.corpus_papers)} manifest papers are fully ingested
						and retrievable today. The knowledge-graph layer (citation graph
						over the corpus){" "}
						{health.corpus_kg_built
							? "has produced its first artifact"
							: "has not yet produced its first production artifact"}{" "}
						— the Corpus page shows exactly that, rather than a synthesized
						graph. Generation requires at least two relevant papers or it
						declines to run.
					</p>
				)}
			</div>
		</div>
	);
}

// ── §10 — Reasoning protocols (Xia et al.) ─────────────────────────────
// Kept panel shape. The retrieval-mechanism line must name the scorer from
// /health.paper_rag rather than asserting one (#778).
const PROTOCOLS = [
	{
		name: "Outcome Embargo",
		what: "Decisions only see papers published before the decision time.",
	},
	{
		name: "Time-Aware Retrieval",
		what: "Relevance decays with paper age, faster in volatile regimes.",
	},
	{
		name: "Hierarchy of Truth",
		what: "When vault execution ships, chain state will outrank the LLM's narrative: the rebalance loop will read holdings from chain, never from model output, and V_check will cap any single position at 60% concentration before a trade is committed. That path is not live — no user vault has been deployed.",
	},
	{
		name: "Source Tracking",
		what: "Every cited paper carries (arXiv ID, version, content hash), anchored with the trace.",
	},
];

function ProtocolsPanel() {
	return (
		<div className="card p-5 mb-7">
			<div className="label mb-3">Enforced mechanisms, not guidelines</div>
			<p className="body mb-3">
				Four protocols from Xia et al. 2026 — the audit of why most
				trading-agent research is unreproducible. Outcome Embargo, Time-Aware
				Retrieval, and Source Tracking run on the generation path today.
				Hierarchy of Truth (read holdings from chain before a trade) is the
				vault-rebalance path, which is not live.
			</p>
			<div className="grid grid-cols-1 md:grid-cols-2 gap-3">
				{PROTOCOLS.map((p) => (
					<div key={p.name} className="card-flat p-3">
						<div className="font-semibold mb-1" style={{ fontSize: "0.92rem" }}>
							{p.name}
						</div>
						<div className="caption" style={{ color: "var(--text-3)" }}>
							{p.what}
						</div>
					</div>
				))}
			</div>
		</div>
	);
}

// ── §11 — What's real today (honesty ledger) ────────────────────────────

const LEDGER_TONES = {
	live: "var(--positive)",
	pending: "var(--warning)",
	roadmap: "var(--info)",
};

function LedgerStatus({ children, tone }) {
	return (
		<strong style={{ color: LEDGER_TONES[tone] ?? "var(--text-3)" }}>
			{children}
		</strong>
	);
}

function HonestyLedger({ health, healthError, agentStatus, agentStatusError }) {
	const loading = !health && !healthError;
	const agentLoading = !agentStatus && !agentStatusError;
	return (
		<div className="card p-5 mb-7">
			<div className="label mb-3">The honest ledger</div>
			<p className="body mb-4">
				Archimedes runs on the Arc public testnet — real contracts, real
				signatures, faucet USDC. No mainnet money; generation settles real
				testnet USDC (read GET /api/generate/quote). Claims must be true on the
				live path; here is the current state, kept current from the system's
				own health surface:
			</p>
			<div className="table-container mb-3">
				<table>
					<thead>
						<tr>
							<th>Surface</th>
							<th>Status today</th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td>Generate → rigor gate → passport</td>
							<td>
								<LedgerStatus tone="live">Live</LedgerStatus> — debate society,
								live tri-state gate
							</td>
						</tr>
						{/* Ungated and roadmap-toned as of the 2026-08-30 claim scrub.
						    This row previously rendered only in the flag-on preview
						    build and asserted "Live — you sign everything; testnet
						    USDC" for a path with zero live user deployments. The
						    honest ledger is the one place the public build should
						    state that plainly, so it now always renders. */}
						<tr>
							<td>On-chain execution + deposits</td>
							<td>
								<LedgerStatus tone="roadmap">Roadmap</LedgerStatus> — contracts
								deployed to testnet, no live user deployments; Archimedes does
								not manage capital today
							</td>
						</tr>
						<tr>
							<td>Commit → trade → reveal provenance</td>
							<td>
								<LedgerStatus tone="roadmap">Roadmap</LedgerStatus> —
								contract-enforced ordering on the vault path; generation
								computes a hash and does not write it on-chain. The trade
								half waits on the execution path above
							</td>
						</tr>
						{ROADMAP_SURFACES_ENABLED && (
							<tr>
								<td>Autonomous rebalance loop</td>
								<td>
									{agentStatusError ? (
										<span style={{ color: "var(--text-4)" }}>
											— live value unavailable
										</span>
									) : agentLoading ? (
										<span
											style={{
												color: "var(--text-4)",
												animation: "pulse 1.4s infinite",
											}}
										>
											···
										</span>
									) : agentStatus.alive ? (
										<>
											<LedgerStatus tone="live">Live</LedgerStatus>{" "}
											— the runner loop is ticking: heartbeat confirmed
											within the last 10 minutes on the dedicated runner
											instance (relocated off the old detached EC2 box,
											#1043/#1065). The heartbeat is written after every
											tick, including a failed one, and independently of
											dry-run — it confirms the loop is alive, not that a
											given tick reached commit/trade/reveal
										</>
									) : (
										<>
											<LedgerStatus tone="pending">
												No recent heartbeat
											</LedgerStatus>{" "}
											— the loop is defined to evaluate, then
											commit/trade/reveal when not in dry-run; no
											heartbeat in the last 10 minutes, so neither uptime
											nor execution is confirmed
										</>
									)}
								</td>
							</tr>
						)}
						{ROADMAP_SURFACES_ENABLED && (
							<tr>
								<td>Marketplace publish / subscribe</td>
								<td>
									<LedgerStatus tone="pending">
										Settlement in dry-run
									</LedgerStatus>{" "}
									— the real x402 pipeline runs end-to-end; final settlement is
									simulated
								</td>
							</tr>
						)}
						<tr>
							<td>Corpus retrieval</td>
							<td>
								{healthError ? (
									<span style={{ color: "var(--text-4)" }}>
										— live value unavailable
									</span>
								) : loading ? (
									<span
										style={{
											color: "var(--text-4)",
											animation: "pulse 1.4s infinite",
										}}
									>
										···
									</span>
								) : health.paper_rag === "live" ? (
									<>
										<LedgerStatus tone="live">Live</LedgerStatus> — keyword +
										MiniLM rerank, scored per request;{" "}
										{fmtNum(health.corpus_db_count)} of{" "}
										{fmtNum(health.corpus_papers)} papers hydrated
									</>
								) : (
									<>
										<LedgerStatus tone="pending">Degraded</LedgerStatus> —
										lexical TF-IDF fallback active
									</>
								)}
							</td>
						</tr>
						<tr>
							<td>Knowledge graph</td>
							<td>
								{healthError ? (
									<span style={{ color: "var(--text-4)" }}>
										— live value unavailable
									</span>
								) : loading ? (
									<span
										style={{
											color: "var(--text-4)",
											animation: "pulse 1.4s infinite",
										}}
									>
										···
									</span>
								) : health.corpus_kg_built ? (
									<>
										<LedgerStatus tone="live">Live</LedgerStatus> — first
										artifact produced
									</>
								) : (
									<>
										<LedgerStatus tone="pending">Not yet</LedgerStatus> —
										pipeline built, first artifact pending
									</>
								)}
							</td>
						</tr>
						<tr>
							<td>Mainnet, real funds</td>
							<td>
								<LedgerStatus tone="roadmap">Roadmap</LedgerStatus> — Arc
								mainnet is upcoming; settlement architecture is an explicit
								deferred decision
							</td>
						</tr>
					</tbody>
				</table>
			</div>
			<p className="caption" style={{ color: "var(--text-3)" }}>
				If a row here ever disagrees with what you see in the product, that's a
				bug — report it. The badge only means something if it can fail.
			</p>
		</div>
	);
}

// ── §12 — CTA ────────────────────────────────────────────────────────

function CallToAction({ onNavigate }) {
	return (
		<div className="card p-5 text-center">
			<h3 className="serif mb-2" style={{ fontSize: "1.4rem" }}>
				Ready to try it?
			</h3>
			<p
				className="body mb-4"
				style={{ color: "var(--text-3)", maxWidth: 520, margin: "0 auto 16px" }}
			>
				{ROADMAP_SURFACES_ENABLED
					? ROADMAP_COPY.ctaLede
					: "Describe a strategy in plain English, then sign in to see it through the rigor gate."}
			</p>
			<div className="flex justify-center gap-3 flex-wrap">
				<button
					className="btn btn-primary"
					onClick={() => onNavigate?.("generate")}
				>
					Generate a strategy →
				</button>
				<button
					className="btn btn-outline"
					onClick={() => onNavigate?.("corpus")}
				>
					Explore the corpus
				</button>
				<button
					className="btn btn-outline"
					onClick={() => onNavigate?.("leaderboard")}
				>
					See the Leaderboard
				</button>
			</div>
		</div>
	);
}

export default function Architecture({ onNavigate }) {
	const {
		contracts,
		contractsError,
		health,
		healthError,
		leaderboard,
		leaderboardError,
		agentStatus,
		agentStatusError,
	} = useArchStats();

	return (
		<main className="page-content">
			<PageHeader />
			<HeroStrip
				contracts={contracts}
				contractsError={contractsError}
				health={health}
				healthError={healthError}
				leaderboard={leaderboard}
				leaderboardError={leaderboardError}
			/>
			{ROADMAP_SURFACES_ENABLED && <SystemFlowDiagram />}
			<PipelineFlow />
			<DebateSociety health={health} healthError={healthError} />
			<RigorGateSection
				leaderboard={leaderboard}
				leaderboardError={leaderboardError}
			/>
			<OnChainExecutionRoadmap
				contracts={contracts}
				contractsError={contractsError}
			/>
			<ProvenanceSection />
			{ROADMAP_SURFACES_ENABLED && <MarketplaceSection />}
			<CorpusSection health={health} healthError={healthError} />
			<ProtocolsPanel />
			<HonestyLedger
				health={health}
				healthError={healthError}
				agentStatus={agentStatus}
				agentStatusError={agentStatusError}
			/>
			<CallToAction onNavigate={onNavigate} />
		</main>
	);
}
