#!/usr/bin/env python3
"""Regenerate nginx/cloudfront-origin-facing.conf from AWS's published IP ranges (#1908).

nginx's realip module must trust CloudFront's ORIGIN-FACING addresses (the ones
CloudFront connects to origins from; AWS ``ip-ranges.json`` service
``CLOUDFRONT_ORIGIN_FACING``) so that ``$remote_addr`` resolves to the viewer
rather than the CloudFront edge. nginx/nginx.conf ``include``s the generated
file; nginx/Dockerfile installs it next to the rendered config.

The list is VENDORED, never fetched at runtime or at image build: the file is
reviewed in a diff like any other trust change, every image built from one
commit trusts the same set, and nginx never depends on reaching AWS to boot.
This script is the one place network I/O for it happens: an explicit,
human-run refresh (same pattern as scripts/refresh_rf_series.py).

The file is rewritten only when the SET of prefixes changes. AWS bumps
``syncToken`` whenever any service's ranges move, which is most days, and a
header-only rewrite would be churn with no trust change in it.

Usage::

    python scripts/refresh_cloudfront_origin_ranges.py           # refresh in place
    python scripts/refresh_cloudfront_origin_ranges.py --check   # exit 1 if stale
    python scripts/refresh_cloudfront_origin_ranges.py --source ip-ranges.json  # offline

Staleness, in both directions:

* AWS ADDS a range we lack: requests relayed from it resolve to the CloudFront
  edge again (the pre-#1908 behaviour) — per-edge rate-limit buckets, not open.
* AWS RETIRES a range we still list: if that space is reassigned, a host there
  could reach the internet-facing ALB directly and have a forged
  X-Forwarded-For hop believed. That is the reason to run ``--check`` regularly.
"""

from __future__ import annotations

import argparse
import ipaddress
import json
import re
import sys
import urllib.request
from pathlib import Path

IP_RANGES_URL = "https://ip-ranges.amazonaws.com/ip-ranges.json"
SERVICE = "CLOUDFRONT_ORIGIN_FACING"
OUTPUT_PATH = Path(__file__).resolve().parent.parent / "nginx" / "cloudfront-origin-facing.conf"

# Sanity floors. A truncated or malformed download must never be written as a
# trust list, and no single entry may be broad enough to trust a large slice of
# the internet. Today's data: 46 IPv4 (/16-/26) + 35 IPv6 (/36-/56) prefixes.
MIN_PREFIXES = 10
MIN_PREFIXLEN = {4: 12, 6: 32}

# Space that must never be trusted from this list (RFC 6890 special-purpose:
# private, shared, loopback, link-local, multicast, reserved). `is_global` alone
# is not enough for a NETWORK: ipaddress judges one by its endpoints, so both
# 0.0.0.0/0 and 192.160.0.0/12 (which contains 192.168.0.0/16) report global.
_NON_PUBLIC = [
    ipaddress.ip_network(n)
    for n in (
        "0.0.0.0/8", "10.0.0.0/8", "100.64.0.0/10", "127.0.0.0/8", "169.254.0.0/16", "172.16.0.0/12",
        "192.0.0.0/24", "192.168.0.0/16", "198.18.0.0/15", "224.0.0.0/3",
        "::/8", "fc00::/7", "fe80::/10", "ff00::/8",
    )
]  # fmt: skip

_LINE = re.compile(r"^set_real_ip_from (\S+);$")
_META = re.compile(r"^# syncToken (\S+), createDate (\S+)\.$")

HEADER = """\
# GENERATED by scripts/refresh_cloudfront_origin_ranges.py - DO NOT EDIT BY HAND.
# Source: {url}
# Service: {service} (the addresses CloudFront connects to origins from).
# syncToken {sync_token}, createDate {create_date}.
# {v4} IPv4 + {v6} IPv6 prefixes.
#
# Included by nginx/nginx.conf next to `set_real_ip_from 10.0.0.0/16;` so realip
# treats the CloudFront hop the ALB appends to X-Forwarded-For as a trusted proxy
# and resolves $remote_addr to the viewer (#1908). See the realip note there.
"""


class RangesError(ValueError):
    """The input cannot be trusted as a CloudFront origin-facing list."""


def _order(net) -> tuple[int, int, int]:
    return (net.version, int(net.network_address), net.prefixlen)


def origin_facing_networks(ip_ranges: dict) -> list[ipaddress.IPv4Network | ipaddress.IPv6Network]:
    """Return the CLOUDFRONT_ORIGIN_FACING prefixes, validated, de-duplicated, sorted."""
    raw = [p["ip_prefix"] for p in ip_ranges.get("prefixes", []) if p.get("service") == SERVICE]
    raw += [p["ipv6_prefix"] for p in ip_ranges.get("ipv6_prefixes", []) if p.get("service") == SERVICE]
    networks = set()
    for text in raw:
        try:
            net = ipaddress.ip_network(text, strict=True)
        except ValueError as exc:
            raise RangesError(f"not a network prefix: {text!r} ({exc})") from exc
        if not net.is_global or any(net.overlaps(x) for x in _NON_PUBLIC if x.version == net.version):
            raise RangesError(f"{net} is not a public range; refusing to trust it")
        if net.prefixlen < MIN_PREFIXLEN[net.version]:
            raise RangesError(
                f"{net} is broader than /{MIN_PREFIXLEN[net.version]}; refusing to trust it without a human look"
            )
        networks.add(net)
    if len(networks) < MIN_PREFIXES or not any(n.version == 4 for n in networks):
        raise RangesError(
            f"only {len(networks)} {SERVICE} prefixes (need >= {MIN_PREFIXES}, incl. IPv4) — truncated download?"
        )
    return sorted(networks, key=_order)


def render(networks, sync_token: str, create_date: str) -> str:
    header = HEADER.format(
        url=IP_RANGES_URL,
        service=SERVICE,
        sync_token=sync_token,
        create_date=create_date,
        v4=sum(1 for n in networks if n.version == 4),
        v6=sum(1 for n in networks if n.version == 6),
    )
    return header + "".join(f"set_real_ip_from {n};\n" for n in networks)


def parse_conf(text: str) -> tuple[list, str, str]:
    """Parse a generated file back into (networks, syncToken, createDate). Strict."""
    networks, meta = [], None
    for number, line in enumerate(text.splitlines(), 1):
        if not line.strip():
            continue
        if line.startswith("#"):
            meta = meta or _META.match(line)
            continue
        match = _LINE.match(line)
        if not match:
            raise RangesError(f"line {number} is not `set_real_ip_from <cidr>;`: {line!r}")
        networks.append(ipaddress.ip_network(match.group(1), strict=True))
    if meta is None:
        raise RangesError("no `# syncToken …, createDate ….` provenance line")
    return networks, meta.group(1), meta.group(2)


def _load(source: str | None) -> dict:
    if source:
        return json.loads(Path(source).read_text(encoding="utf-8"))
    with urllib.request.urlopen(IP_RANGES_URL, timeout=30) as response:
        return json.load(response)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n", 1)[0])
    parser.add_argument("--check", action="store_true", help="exit 1 if the vendored set differs; write nothing")
    parser.add_argument("--source", help="read ip-ranges.json from this file instead of the network")
    parser.add_argument("--output", type=Path, default=OUTPUT_PATH, help=argparse.SUPPRESS)
    args = parser.parse_args(argv)

    data = _load(args.source)
    fresh = origin_facing_networks(data)
    current: list = []
    if args.output.exists():
        current, _, _ = parse_conf(args.output.read_text(encoding="utf-8"))

    added = sorted(set(fresh) - set(current), key=_order)
    removed = sorted(set(current) - set(fresh), key=_order)
    for net in added:
        print(f"+ {net}")
    for net in removed:
        print(f"- {net}")

    if not added and not removed and current:
        print(f"{args.output.name}: up to date ({len(current)} prefixes)")
        return 0
    if args.check:
        print(f"{args.output.name}: STALE (+{len(added)} -{len(removed)}) — run {Path(__file__).name}")
        return 1
    args.output.write_text(render(fresh, str(data["syncToken"]), str(data["createDate"])), encoding="utf-8")
    print(f"{args.output.name}: wrote {len(fresh)} prefixes (+{len(added)} -{len(removed)})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
